### ISSUE TITLE
Add speed layer to process measurement in less than 1h

### ISSUE THREAD

**Issue by hellais** [ooni/backend#129]
Currently the `ooni/pipeline` has a 24h batch process which is used to compress measurement for long-term archival (`canning`), extract features to go into the DB (`centrifugation`) and then expose these in OONI API.

This means that from the moment a user runs an experiment, to them moment they are available in OONI API (and hence OONI Explorer) it can take up to 24h.

One thing that we were discussing was the possibility of having a [speed layer](https://en.wikipedia.org/wiki/Lambda_architecture#Speed_layer), which processes measurements as soon as they are submitted to the collector. This would allow us to at least expose some basic metrics for submitted measurements (at least show the file and acknowledge their existence).

Some more advanced features that are harder to do in real-time (for example sim-hash detection or other more sofisticated heuristics), don't necessarily have to happen here.

This would be especially useful for: https://github.com/ooni/probe/issues/816

**Comment by bassosimone** [comment]
@hellais isn't this done?

**Comment by hellais** [comment]
Yes it is! yay!
