### ISSUE TITLE
Improve performance for EG query on OONI Explorer

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#144]
This query (linked in the Highlights section of the landing page of the new OONI Explorer) is quite odd: https://explorer-beta.ooni.io/search?domain=madamasr.com&probe_cc=EG&test_name=web_connectivity&since=2018-04-01&until=2018-07-02

Sometimes it works, and other times it doesn't (displaying an error page). I have noticed this multiple times (that sometimes it works, others it doesn't), whereas the other queries linked from the Highlights page are more consistent (as in, they always work).

It may therefore be worth looking into the performance of this query.

**Comment by FedericoCeratto** [comment]
Fixed by moving to ClickHouse. Currently the query takes approx 1 second.
