### ISSUE TITLE
Explorer queries that don't work

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#146]
The following queries don't seem to work on OONI Explorer, leading to "unknown errors":

https://explorer.ooni.org/search?until=2019-09-14&domain=antivigilancia.org&probe_cc=BR

https://explorer.ooni.org/search?until=2019-09-14&domain=ooni.io

The domain in the 1st query does not appear to be included in the test lists (I just added it: https://github.com/citizenlab/test-lists/pull/506/commits/0b9f9f5f36cfcbcdd64278854acb7f9ddfc6ac3b) and should therefore render a "Results not found" message, unless if it has been tested nonetheless and it's a server-side issue on our end.

**Comment by hellais** [comment]
These now work.
