### ISSUE TITLE
Improve performance for OONI Explorer query

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#148]
It would be great if the performance of the following query was improved: https://explorer.ooni.org/search?until=2019-09-24&domain=www.bbc.com&probe_cc=EG&probe_asn=AS8452

The first few times I tried it it didn't seem to work, as it rendered a server error. Eventually it loaded, suggesting that it works, but the performance needs to be optimized.

**Comment by FedericoCeratto** [comment]
Implemented in https://github.com/ooni/backend/issues/437
