### ISSUE TITLE
IR Explorer query results in error

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#151]
This query: https://explorer.ooni.org/search?until=2019-09-05&domain=www.womenonwaves.org&test_name=web_connectivity&probe_cc=IR

...results in the following error:

{
  "detail": [
    "The database query timed out.",
    "Try changing the query parameters."
  ],
  "status": 504,
  "title": "Gateway Timeout",
  "type": "about:blank"
}

**Comment by hellais** [comment]
These now work
