### ISSUE TITLE
JO Explorer query results in error

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#152]
This query: https://explorer.ooni.org/search?until=2019-10-15&domain=www.womenonwaves.org&probe_cc=JO

...results in the following error:

{
  "config": {
    "transformRequest": {},
    "transformResponse": {},
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "headers": {
      "Accept": "application/json, text/plain, */*"
    },
    "baseURL": "https://api.ooni.io",
    "method": "get",
    "params": {
      "probe_cc": "JO",
      "domain": "www.womenonwaves.org",
      "until": "2019-10-15",
      "limit": 50
    },
    "url": "https://api.ooni.io/api/v1/measurements"
  },
  "response": {
    "data": {
      "detail": [
        "The database query timed out.",
        "Try changing the query parameters."
      ],
      "status": 504,
      "title": "Gateway Timeout",
      "type": "about:blank"
    },
    "status": 504,
    "statusText": "GATEWAY TIMEOUT",
    "headers": {
      "content-type": "application/problem+json",
      "content-length": "172"
    },
    "config": {
      "transformRequest": {},
      "transformResponse": {},
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "headers": {
        "Accept": "application/json, text/plain, */*"
      },
      "baseURL": "https://api.ooni.io",
      "method": "get",
      "params": {
        "probe_cc": "JO",
        "domain": "www.womenonwaves.org",
        "until": "2019-10-15",
        "limit": 50
      },
      "url": "https://api.ooni.io/api/v1/measurements"
    },
    "request": {
      "__sentry_xhr__": {
        "method": "GET",
        "url": "https://api.ooni.io/api/v1/measurements?probe_cc=JO&domain=www.womenonwaves.org&until=2019-10-15&limit=50",
        "status_code": 504
      }
    }
  }
}

**Comment by hellais** [comment]
Now this query is working.
