### ISSUE TITLE
ES queries don't work

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#153]
The following OONI Explorer queries don't work and result in gateway timeout errors:

https://explorer.ooni.org/search?until=2019-10-22&domain=app.tsunamidemocratic.cat&probe_cc=ES

https://explorer.ooni.org/search?until=2019-10-22&domain=tsunamidemocratic.github.io&probe_cc=ES

These queried domains were reportedly blocked in Spain recently.

**Comment by hellais** [comment]
These queries now work
