### ISSUE TITLE
RU query which does not work

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#154]
The following OONI Explorer query: https://explorer.ooni.org/measurement/20190809T091511Z_AS8402_x2k2mWMb1yJJ3mWYtRY36PGpSdZOOGmvl4ANndzrXi625l7fVz?input=http%3A%2F%2Fwww.womenonwaves.org%2F

...claims that "Results are not found", an error which usually appears if there are no measurements available based on the specific query. 

However, there are certainly measurements available based on that query, because this measurement exists from that network: https://explorer.ooni.org/measurement/20190809T091511Z_AS8402_x2k2mWMb1yJJ3mWYtRY36PGpSdZOOGmvl4ANndzrXi625l7fVz?input=http%3A%2F%2Fwww.womenonwaves.org%2F

I also recall doing this query several weeks ago and it worked at the time... not sure what might have "broken" in the meanwhile.

**Comment by hellais** [comment]
These queries now work
