### ISSUE TITLE
ID query for "confirmed blocked" not working

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#155]
The following OONI Explorer query does not work: https://explorer.ooni.org/search?until=2019-10-24&probe_cc=ID&test_name=web_connectivity&only=confirmed

This query (which aims to get the "confirmed blocked" Web Connectivity measurements from Indonesia) says "Results not found", an error which usually is displayed when there are no measurements available.

However, given that we have the ID blockpage fingerprints, this query should render results.

**Comment by hellais** [comment]
This has been fixed. Closing.
