### ISSUE TITLE
Rewrite list_measurements

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#160]
- Faster
- Without SQLAlchemy objects
- Fix union bugs
- Implement merge strategy and write extensive tests:
  - msmt in fastpath only
  - msmt in both fastpath and pipeline: feed body from S3 cans
  - msmt in pipeline only
- Speed up integ test where possible

ooni/api#135 depends on ooni/api#148

**Comment by hellais** [comment]
We have re-written the list_measurements API which has resulted in a significant performance boost.

Some bugs were spotted during the implementation, but fixed all the ones we could find and wrote integration tests for them.

Closing this issue.
