### ISSUE TITLE
Removing some false positives

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#171]
To remove *some* of the false positives that are exposed via OONI Explorer, perhaps the following could be implemented:

**1. Filter all web connectivity, "anomalous", HTTP-diff measurements and detect those that present cloud-flare.** Then tag those measurements as false positives, or put them in a different database.

**2. Detect URLs that fail in the same way around the world and filter them out as false positives.** rapidshare.com is an example of this.

**Comment by hellais** [comment]
This is a very old issue. I am going to close this.
