### ISSUE TITLE
Add support for OOID

### ISSUE THREAD

**Issue by hellais** [ooni/backend#173]
Update 2019-06-21:

The next steps are to implement what is described in: https://github.com/ooni/pipeline/blob/master/docs/ooni-uuid.md
* [ ] Add OOID annotation supports in collector: https://github.com/ooni/collector/pull/3
* [ ] Backfill all the OOID in legacy measurements
* [ ] Add OOID support for clients
* [ ] Update API to use OOID
* [ ] Update explorer to redirect to the new OOID

Currently we are using (inside of ooni-explorer) as an identifier for a given measurement the tuple (report_id, input).

This is problematic for a variety of reasons including:

* It's not possible to have any type of ordering on this identifier
* The report_id is submitted by the client so collisions are possible (due to maliciously crafted requests)
* Using a tuple for the identifier of a measurement makes it not so nice to share the identifier around
* Indexing on a tuple is not so nice

Moreover we currently have a bug where some of the values of input turn out to be None, making it impossible to access from the explorer certain report ids.

As such I would like us to have a new scheme for measurement IDs with the following requirements:

1. Every ID should be representable as a 64 bit unsigned integer (I guess this can be loosened a bit and we can use 128 bit unsigned integers).

2. It should be possible to regenerate in a deterministic way the measurement identifiers from historical ooni data.

3. There should be ordering on the measurement IDs so that given a certain measurement ID, it should be possible for a certain user to retrieve all measurements **submitted** after that measurement (note: since it's possible to upload measurements from the past it's not possible to have an assurance over the ordering of measurement time)

4. We should be able to generate up to 15k measurement IDs per second (this estimate is based on the fact that an upper bound on measurements a client generates is 10k, we want this to scale to at least 100k daily clients => 1G measurements/day = 15K IDs/s)

I had some sort of proposal for what scheme we can use, but it's going to depend greatly on how we are going to be batching up processing of reports and how we handle the data processing lifecycle so I will just give a high level overview of what I was thinking.

The most significant bits should be in some way derived from the bucket date and concatenated with some bits from the timestamp of the test start time. The least significant bits should be derived from the report_id, the input and possible a counter based on increments inside of the measurements in a specific report.

Something like the following:

```
ID = {
bucket_timestamp,
test_start_time,
hash(report_id, input),
counter
}
```
cc @darkk

**Comment by FedericoCeratto** [comment]
Implemented in https://github.com/ooni/backend/issues/437
