### ISSUE TITLE
Make sure body is properly normalized across implementations

### ISSUE THREAD

**Issue by bassosimone** [ooni/backend#174]
Currently [ooniprobe uses a Pythonish strategy for encoding bodies](https://github.com/TheTorProject/ooni-probe/blob/fbaa1758bb426583154c65560ee5a38629819486/ooni/common/http_utils.py#L7). What [I plan to do with MK is simpler](https://github.com/measurement-kit/measurement-kit/issues/970). We should make sure that the pipeline can cope with body formats and is always able to properly normalize the bodies and perform comparisons in the right way. (This is meant as a *defensive* issue: things may work correctly but we should make sure that this is the case in general.)

**Comment by hellais** [comment]
Closing because done
