### ISSUE TITLE
Define metrics and alarms regarding "failed" measurements

### ISSUE THREAD

**Issue by hellais** [ooni/backend#194]
This entails:

* [ ] Defining how this metric looks like
* [ ] Adding to the pipeline documentation about this failed metric
* [ ] Defining a procedure for how these failed measurements should be handled

**Comment by hellais** [comment]
This may have relevant context for @FedericoCeratto, thought should be closed in light of: https://github.com/ooni/backend/issues/286. I will let him close it once that context has been acquired.

**Comment by FedericoCeratto** [comment]
Done
