### ISSUE TITLE
Improve event detector

### ISSUE THREAD

**Issue by hellais** [ooni/backend#207]
@FedericoCeratto was mentioning that we need to fine tune the thresholds for the event detector which is going to be generating an RSS feed (see: https://github.com/ooni/pipeline/issues/229 & https://github.com/ooni/pipeline/pull/228).

We now have setup a web server which generates charts that are useful to understanding how reliable the event detection logic is.

Here is a list of example charts:
http://fastpath.ooni.nu:8080/webapp/chart?cc=BR&test_name=web_connectivity&input=https%3A%2F%2Fwww.womenonwaves.org%2F&start_date=2016-1-1
http://fastpath.ooni.nu:8080/webapp/chart?cc=EG&test_name=web_connectivity&input=https%3A%2F%2Fwww.womenonwaves.org%2F&start_date=2016-1-1

What we are looking at in the above charts (@FedericoCeratto please correct me if I am wrong) is:

* The x axis is time, the y axis is the score, higher means more likely to be blocked, lower means less likely
* The blue line is a moving average of the score given to a particular (country, input) pair based on the scores from other measurements
* The green dots represent a single measurement and it's score
* The red bar means that some censorship event was detected in there

What needs to be done here is to look at the above charts and try to understand how well they capture censorship changes (when a site went from unblocked to blocked or vice-versa) and if not so accurate go in and tweak some parameters.

**Comment by FedericoCeratto** [comment]
This is part of https://github.com/ooni/backend/issues/509

**Comment by hellais** [comment]
This is no longer releveant.
