### ISSUE TITLE
Data analysis: Blocking of LGBTQI sites globally

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#224]
This analysis involves analyzing all Web Connectivity measurements ever collected (from all countries around the world) that have the **LGBT category code** (https://github.com/citizenlab/test-lists/blob/master/lists/00-LEGEND-new_category_codes.csv) from the Citizen Lab test lists (https://github.com/citizenlab/test-lists/tree/master/lists).

The analysis should produce a CSV file that contains the (LGBT-categorized) URLs that presented anomalies, the type of anomaly that each URL presented (HTTP-diff, HTTP-failure, DNS, TCP/IP), ASNs, date & time of anomalous measurement, their respective OONI Explorer measurements, etc.

**Deadline = 13th December 2019**

**Comment by hellais** [comment]
I have done an initial analysis of this fitting all of the above specifications and moreover focusing on the confirmed blocked sites.

I am closing this issue and suggest we file another one with more specific next steps if we need to do that as part of the next cycle.
