### ISSUE TITLE
Upload measuremests to s3 or object store faster, from collector or fastpath

### ISSUE THREAD

**Issue by hellais** [ooni/backend#228]
Migrated from: https://github.com/ooni/pipeline/issues/265#issue-528103052

**Comment by FedericoCeratto** [comment]
Progress so far: tested upload/dload performance using S3 and obj store. Performance are constant for files above 10 to 50MB. Smaller uploads are heavily impacted by an almost fixed time of 1 to 1.5s.
Filesystems over S3/objstore are unusable.
Investigating zstd as a way to (incrementally) compress msmt using a fixed, shared dictionary.

**Comment by hellais** [comment]
@FedericoCeratto mentions that the next step is to do a follow up investigation on Zstd performance and use-cases

**Comment by FedericoCeratto** [comment]
Implemented in https://github.com/ooni/api/pull/192

**Comment by FedericoCeratto** [comment]
Completed in https://github.com/ooni/backend/issues/437
