### ISSUE TITLE
research: brainstorm simplified collector

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#230]
https://docs.google.com/document/d/1JR-_seBk2JXoY9aGaTIwWBtmtsgvO-An0B9Wk9to-28

**Comment by hellais** [comment]
Within the context of this, we have discussed that we likely want a single code-base for everything related to backend, including the collector.

Probably we want to consolidate `ooni/orchestra/orchestrate` and `ooni/orchestra/registry` into a single repo, perhaps `ooni/backend`.

We also talked about the requirements for the collector and that we are going to proceed with the plan of having a single API call that is `/api/v1/measurement`, but that the underlying logic is identical to what we discussed in the above document (i.e. `POST /report/${report_id}`) for backward compatibility.

**Comment by bassosimone** [comment]
To close the feedback look, we need to share what we concluded with @FedericoCeratto and then prepare an actionable plan for replacing the collector. Hopefully we can do the above soon?

**Comment by hellais** [comment]
Yes! I added this as an agenda item for the weekly backend dev meeting tomorrow.

**Comment by hellais** [comment]
I would say the discussion of this topic has been done during this cycle, it's now a matter of working towards the implementation.

I have created an epic for this: https://github.com/ooni/backend/issues/310
