### ISSUE TITLE
Fastpath: keep rows in fastpath table

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#233]
Delete json files of disk but keep the row in the db table
Check how the API is going to handle this.
Implement integ tests in the API

**Comment by hellais** [comment]
Was this done during this sprint?

**Comment by hellais** [comment]
As part of this effort we will also be re-running the fastpath against historical data to detect new blockpages.

**Comment by FedericoCeratto** [comment]
Tweak API: set measurement_url to feed from traditional pipeline.
Tweak fastpath: delete files of disk but leave row

**Comment by FedericoCeratto** [comment]
https://github.com/ooni/api/pull/171

**Comment by FedericoCeratto** [comment]
https://github.com/ooni/pipeline/pull/309 is deployed

**Comment by hellais** [comment]
This is deployed and merged.
