### ISSUE TITLE
Tighten TLS settings

### ISSUE THREAD

**Issue by darkk** [ooni/backend#238]
[bouncer.ooni.io](https://www.ssllabs.com/ssltest/analyze.html?d=bouncer.ooni.io) and some other API endpoints are not PFS-enabled, chrome is upset saying
> _The connection to this site uses an obsolete protocol (TLS 1.0), an obsolete key exchange (RSA), and an obsolete cipher (AES_128_CBC with HMAC-SHA1)._

It may be improved, but I mark it as `low-priority` as (AFAIK) no confidential data is transmitted to OONI, so the only benefit from TLS is integrity.

**Comment by FedericoCeratto** [comment]
Implemented in https://github.com/ooni/backend/issues/437
