### ISSUE TITLE
Set `node` GC parameters

### ISSUE THREAD

**Issue by darkk** [ooni/backend#246]
There should be some "right" way to set `node` GC parameters for `node` binary. It's not unclear to me if hardcoding the value into [package.json](https://github.com/ooni/run/blob/master/package.json) is the right way (given that `yarn` is used as a launcher at ooni/run#14 & ooni/run#15, I'm also unsure if `yarn` does anything before launching `/bin/sh -c "$arg"`).

I believe, that one of the reasons for recurring _[FIRING] run.ooni.io:9100 has 9% RAM available_ alerts is that the `node` GC expect to run at the [VM having 1.5GiB of RAM at least per linked post](https://blog.risingstack.com/finding-a-memory-leak-in-node-js/).

![ooni-run 2018-12-19 12-41-30](https://user-images.githubusercontent.com/21046/50212692-b5170400-038c-11e9-9d36-31e00695077c.png)

Those false alarms contribute to alert fatigue (firing several times a day), so I'd like to see them silent. As soon as OONI Run runs fine on 512 MiB VM, I'd suggest to try to tune GC setting before bumping VM size to 2 GiB.

**Comment by FedericoCeratto** [comment]
Obsoleted.
