### ISSUE TITLE
Update ntp configuration in dom0

### ISSUE THREAD

**Issue by bassosimone** [ooni/backend#249]
It should be possible to move ntp to dom0 and get the ntp data from xen. To do this, we should make sure whether this is a config supported by GreenHost.

Having ntp in dom0 is advisable because ntp in domU is subject to more fluctuations.

**Comment by bassosimone** [comment]
@FedericoCeratto @hellais it seems to me this can't be done, right?

**Comment by bassosimone** [comment]
I am going to remove myself from this issue.

**Comment by FedericoCeratto** [comment]
Closing after moving to new service.
