### ISSUE TITLE
Redirect new Explorer to the SSL version by default

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#252]
I guess this is quite self-explanatory (and it was pointed out by people on social media).

**Comment by hellais** [comment]
Maybe the issue of supporting such legacy clients isn't really that important and in light of the fact that we will eventually have authentication on OONI Explorer I think we should go ahead and do this.

Bumping this up in priority.

**Comment by hellais** [comment]
This has been done.

Closing.
