### ISSUE TITLE
Rate limiting on exposed services

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#260]
Some calls against exposed services are resource intensive, e.g. API calls that run database queries.
- Implement ipaddr-based rate limiting with different thresholds based  service and call
- document it for end users

**Comment by FedericoCeratto** [comment]
Required to improve https://github.com/ooni/backend/issues/371

**Comment by hellais** [comment]
This is superseeded by: https://github.com/ooni/backend/issues/394
