### ISSUE TITLE
Implement the pipeline/fastpath ansible playbook

### ISSUE THREAD

**Issue by hellais** [ooni/backend#267]
This is basically landing the following PR: https://github.com/ooni/sysadmin/pull/380/files

**Comment by hellais** [comment]
I updated the issue title with a more descriptive title.

In order to consider this done what needs to happen is:

1. Write documentation on how to create a new .deb package for the fastpath
2. Update the ooni/fastpath PR (https://github.com/ooni/sysadmin/pull/380/files) to use said deb package via the ansible playbook to make the deployment consistent with the rest of our infra

**Comment by FedericoCeratto** [comment]
Implemented in https://github.com/ooni/backend/issues/437
