### ISSUE TITLE
Create pre-production/staging/gamma environment 

### ISSUE THREAD

**Issue by hellais** [ooni/backend#273]
When discussing with @FedericoCeratto the improvements related to fastpath, pipeline, api and explorer integration, the need came up to have a staging environment.

This would allow us try out new features for OONI Explorer and API without necessarily shipping them to end users.

**Comment by hellais** [comment]
We discussed this during the weekly backend meeting.

@FedericoCeratto is going to setup a new host on eclips.is to start experimenting with setting up a staging host.

**Comment by hellais** [comment]
We discussed in the team meeting to use the gamma host as an example to setup OONI stack in ssdams.infra.ooni.io

**Comment by FedericoCeratto** [comment]
Done.

**Comment by hellais** [comment]
We now have a testing host called ams-pg-test.ooni.org, which has a copy of all our infrastructure running on it.
