### ISSUE TITLE
webconnectivity uses the new test helper (oohelperd)

### ISSUE THREAD

**Issue by bassosimone** [ooni/backend#275]
The next steps for this are:

* Try to expose via ps.ooni.io: https://github.com/ooni/probe-cli/tree/master/internal/cmd/oohelperd

**Comment by hellais** [comment]
I would say the priority of this is not necessarily so high and we can perhaps get away with just doing the simple fix of: https://github.com/ooni/backend/issues/274 as an interim solution.

**Comment by bassosimone** [comment]
@hellais I am starting to think that we should never "schedule" an XL activity. My insight is that when something is XL we can probably split it. Agree that finishing the test helper is not high prio. I have created a significantly smaller issue (#276) to start moving us in that direction.

**Comment by hellais** [comment]
Yes I agree with you. I converted this issue into an epic and I suggest we add to it all the smaller chunks of work which can be done via this.

**Comment by hellais** [comment]
We have made considerable progress on this item. We have roaming test helpers which deploy the web connectivity test helper, but we have yet to deploy it in production.

**Comment by bassosimone** [comment]
I briefly created https://github.com/ooni/probe/issues/1716, but then realized it was simpler to just rename this epic.

**Comment by hellais** [comment]
We have the ability the have the test helper, but we haven't switched yet.

Currently only simone is using the new test helper.

The next steps are to verify if it's working as expected and then do the switch.

**Comment by bassosimone** [comment]
Today we're rolling out all probes to the new TH: https://github.com/ooni/api/pull/294. We'll monitor the situation for 24h and then decide whether to roll back or keep using the new TH.

**Comment by bassosimone** [comment]
I think we can say we did this. Unless there are unexpected surprises, all probes should now use the new TH.
