### ISSUE TITLE
letsencrypt: update client to use ACMEv2 protocol

### ISSUE THREAD

**Issue by bassosimone** [ooni/backend#277]
```
Hi,

According to our records, the software client you're using to get Let's
Encrypt TLS/SSL certificates issued or renewed at least one HTTPS certificate
in the past two weeks using the ACMEv1 protocol. [snip]

Beginning June 1, 2020, we will stop allowing new domains to validate using
the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before
then, or certificate issuance will fail. 

[snip]
```

**Comment by hellais** [comment]
It's probably useful to also mention that the IPs of the machines are:
* 37.218.245.43 (which corresponds to prometheus, for which we have an issue to upgrade it: https://github.com/ooni/backend/issues/264)
* 54.221.146.227 (which corresponds to the AWS host used by DW)

**Comment by bassosimone** [comment]
@hellais thanks and also thanks for setting the effort properly. I guess mine was an estimate that was factoring in also the psychological cost of understanding what to do :-P.

**Comment by hellais** [comment]
I have updated both of these hosts to the latest certbot packages. Closing.
