### ISSUE TITLE
Some measurements are now not accessible from the list_measurement API endpoint

### ISSUE THREAD

**Issue by hellais** [ooni/backend#278]
Originally reported by @lorenzoPrimi in https://github.com/ooni/probe-android/pull/281#issuecomment-574581543.

You can see that currently:
https://api.ooni.io/api/v1/measurements?report_id=20190113T202156Z_AS327931_CgoC3KbgM6zKajvIIt1AxxybJ1HbjwwWJjsJnlxy9rpcGY54VH yields no results, while running:

```
SELECT * FROM measurement JOIN report USING (report_no) WHERE report_id = '20190113T202156Z_AS327931_CgoC3KbgM6zKajvIIt1AxxybJ1HbjwwWJjsJnlxy9rpcGY54VH';
```

produces one row:

```
7294447	263478291	5429126	53216	222173	4308	2019-02-22 20:21:59	33,50583		a2a753f4-77e2-425b-8f00-4e1ca2bea65d			1093713				241221	2019-02-22 20:21:47	DZ	327931		ndt		2019-01-13/20190222T202147Z-DZ-AS327931-ndt-20190113T202156Z_AS327931_CgoC3KbgM6zKajvIIt1AxxybJ1HbjwwWJjsJnlxy9rpcGY54VH-0.2.0-probe.json		20190113T202156Z_AS327931_CgoC3KbgM6zKajvIIt1AxxybJ1HbjwwWJjsJnlxy9rpcGY54VH	916
```

I suspect this happened following the recent OONI API optimisations.

cc @FedericoCeratto

**Comment by FedericoCeratto** [comment]
It's also not showing on https://explorer.ooni.org/search?until=2019-02-23&probe_cc=DZ&test_name=ndt&since=2019-02-21
