### ISSUE TITLE
Ensure that the API gives priority for data coming from the fastpath table

### ISSUE THREAD

**Issue by hellais** [ooni/backend#283]
We will ensure that the API always gives priority for data coming from the fastpath column and should failover to the batch pipeline only when the data is missing (for example for historical data).

**Comment by bassosimone** [comment]
@hellais I think we should triage this issue so it's assigned to someone?

**Comment by hellais** [comment]
This is an issue for @FedericoCeratto. I am not sure it should go in this sprint, but if it should there should be an effort estimate.
