### ISSUE TITLE
Certain results not appearing in list_measurements

### ISSUE THREAD

**Issue by hellais** [ooni/backend#287]
As reported on our channels. These queries yield no results:
https://explorer.ooni.org/search?until=2020-01-17&domain=www.sslforfree.com&probe_cc=IR&test_name=web_connectivity
https://explorer.ooni.org/search?until=2020-01-17&domain=www.hmailserver.com&probe_cc=IR&test_name=web_connectivity

While if I do:
```
 SELECT COUNT(*) FROM 
 measurement                     
 JOIN report ON report.report_no = measurement.report_no 
 JOIN input ON input.input_no = measurement.input_no    
 WHERE 
 input LIKE '%www.hmailserver.com%'
    AND report.probe_cc = 'IR';
```
and
```
 SELECT COUNT(*) FROM 
 measurement                     
 JOIN report ON report.report_no = measurement.report_no 
 JOIN input ON input.input_no = measurement.input_no    
 WHERE 
 input LIKE '%www.sslforfree.com%'
    AND report.probe_cc = 'IR';
```

I get 16 rows.

I suspect this may have something to do with the `domain_input` table not have synched data, because if I run:
```
SELECT * FROM domain_input WHERE domain = 'www.sslforfree.com';

SELECT * FROM domain_input WHERE domain = 'www.hmailserver.com';
```

I will get zero rows.

cc @FedericoCeratto

**Comment by FedericoCeratto** [comment]
```
WHERE domain LIKE '%sslforfree%'  gives 0 results
WHERE domain LIKE '%hmailser%' returns:
     domain      |         input          | input_no 
-----------------+------------------------+----------
 hmailserver.com | hmailserver.com        |   401787
 hmailserver.com | hmailserver.com:80     |  1394615
 hmailserver.com | http://hmailserver.com |  3840040

```

**Comment by FedericoCeratto** [comment]
'https://www.sslforfree.com/' is in input but not in domain_input.  There are no entries in faspath at the moment but 3 rows in `measurement` from 2020-01-01

**Comment by hellais** [comment]
@FedericoCeratto can we maybe backfill the domain_input from all historical data?

**Comment by FedericoCeratto** [comment]
We are filling domain_input from input, after validating each row. I'm adding debugging code to check why that URL is not treated as valid.

**Comment by FedericoCeratto** [comment]
Now both URL are working :)

**Comment by FedericoCeratto** [comment]
PR merged
