### ISSUE TITLE
Experiment msmt count table

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#292]
Create a table indexed by probe_cc, asn, *day*, test_name and so on that contains the count of the available msmt
Benchmark queries against it.
Explore the benefit of using it from list_measurements to estimate the cost of queries and avoid pointless queries that will lead to timeouts or huge lists of results

**Comment by FedericoCeratto** [comment]
PR: https://github.com/ooni/pipeline/pull/288

**Comment by hellais** [comment]
Merged into an integration branch. Closing.
