### ISSUE TITLE
Implement API call to extract metrics from counters table (in JSON and CSV)

### ISSUE THREAD

**Issue by hellais** [ooni/backend#321]
Add public/private APIs to count msmts with grouping by cc, input, citizenlab category, date range, test_name and provide anomaly/confirmed/failure/total ratios.

Related to: ooni/explorer#392 & ooni/explorer#391

**Comment by hellais** [comment]
This came from ooni/backend#234

**Comment by FedericoCeratto** [comment]
Design:
A new API call will return data
- in JSON format, by default, on in CSV format when `format=csv` is added the call
- as a 1-dimension structure that fits well into a chart, e.g. number of msmt per day, or
- as a 2-dimension table that fits well into a heatmap, e.g. number of msmt over day (x axis) over CC (y axis)
- optionally cache outputs in the API or on nginx using etags?

**Comment by hellais** [comment]
This has been implemented in the following PR: https://github.com/ooni/api/pull/178

**Comment by hellais** [comment]
I approved and merged the PR. Closing!
