### ISSUE TITLE
Unreachable measurements in the API

### ISSUE THREAD

**Issue by hellais** [ooni/backend#329]
Some measurements result in 404 errors when accessing them via explorer:

https://explorer.ooni.org/measurement/20200208T181202Z_AS44244_7et5KTWKrH9KKYisg1v74rzUv8be4CMBo84ZJu1tR92MfRwg13?input=https://iranrevival.com
https://explorer.ooni.org/measurement/20200208T181508Z_AS197207_3LZ614oENz9AMxx4bsyGQfbUs5LSPCc8ZUAjIdbgl2Pzei5nJU?input=https://iranrevival.com
https://explorer.ooni.org/measurement/20200208T181354Z_AS58224_34sacIE6vqFHBYKNZ3NXqFh6EmzUlZAje0hrBYdMxEmDcT9jMX?input=https://iranrevival.com

But can be accessed fine by querying amsmetadb and getting the direct API link, example: https://api.ooni.io/api/v1/measurement/temp-id-380912001.

**Comment by FedericoCeratto** [comment]
'%iranrevival%' is not matching anything in domain_input.input

**Comment by FedericoCeratto** [comment]
Re-run domain_input_updater, now it works
