### ISSUE TITLE
Move all service configuration into /etc/

### ISSUE THREAD

**Issue by hellais** [ooni/backend#353]
It was brought up during the backend meeting we should put all configuration related to services inside of `/etc/ooni` with etckeeper running.

```
/etc/ooni/<component>  (dir)
/etc/ooni/<component>.conf    (file)
/etc/ooni/api.conf → symlink → /etc/ooni/api.test_database.conf  VS prod_db
/etc under etckeeper
```

**Comment by FedericoCeratto** [comment]
Implemented in https://github.com/ooni/backend/issues/437
