### ISSUE TITLE
Re-run fastpath with historical data

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#372]

**Comment by FedericoCeratto** [comment]
Lowered estimate to 13: first chunk of work is to rerun the fastpath only over one year.

**Comment by FedericoCeratto** [comment]
Reingestion for year 2019 is currently running. https://github.com/ooni/pipeline/pull/318 is related

**Comment by hellais** [comment]
I believe we have interrupted the re-ingestion, due to running out of disk space on the hkgmetadb.

Moving it back to in-progress column.

**Comment by FedericoCeratto** [comment]
Blocked until both HKG and AMS get a disk space increase.

**Comment by hellais** [comment]
I added as blocker: https://github.com/ooni/backend/issues/423

**Comment by FedericoCeratto** [comment]
Done as part of https://github.com/ooni/backend/issues/437
