### ISSUE TITLE
Create countly plugin prototype for selecting push notification targets by country code

### ISSUE THREAD

**Issue by hellais** [ooni/backend#378]
As part of ooni/probe#1055 we determined that we need to understand if it's possible to extend countly community edition functionality to support sending push notifications by country code.

The database view of countly appears to already include country information which is derived from GeoIP, so we should be able to query this in order to filter the targets of push notifications.

![Screenshot 2020-03-25 at 15 38 31](https://user-images.githubusercontent.com/424620/77548394-c794bd00-6eae-11ea-9ba0-bf93b020cd96.png)

The docs for countly are here: https://support.count.ly/hc/en-us/articles/360036862392-Introduction.

Also related to ooni/probe#1057.

**Comment by sarathms** [comment]
The plugin has been created and is in a working state. There are a few rough edges like duplicate countries shown in the dropdown which needs to be addressed.

**Comment by hellais** [comment]
We now have a working prototype of this here: https://github.com/ooni/countly-push-to-country.

It seems like it's possible to do this using the countly plugin API.

We will document some follow up next steps for this to deploy it in production.
