### ISSUE TITLE
Investigate alternative databases

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#385]
Investigate datastores for 2 different usecases:

- Replace PG with a more suitable alternative
- Keep PG in place and replace Pandas and the counters table on PG with an alternative

Options:
- clickhouse - see related issue
- https://prestodb.io/
- https://druid.apache.org/
- https://kylin.apache.org/

**Comment by hellais** [comment]
We should investigate the adoption of BigQuery

**Comment by FedericoCeratto** [comment]
Completed
