### ISSUE TITLE
Next steps for clickhouse testing

### ISSUE THREAD

**Issue by hellais** [ooni/backend#389]
- Test for OOM with parameters from https://github.com/ClickHouse/ClickHouse/issues/9945
- Perhaps receive feedback / updates from package maintainer (?)
- More steps TBD depending on output of tests and other work priorities

**Comment by hellais** [comment]
I will also be spending some time looking at this in this sprint.

**Comment by hellais** [comment]
Currently the clickhouse database does not have all the data I need in order to test this out for real-world data analysis tasks.

As such I can't really do a real test of it. I am moving this into the future sprint and marking it as blocked by: https://github.com/ooni/backend/issues/410

**Comment by FedericoCeratto** [comment]
Finished
