### ISSUE TITLE
Setup new database host in AMS

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#400]
Setup the host:
```
Configuration: ams-box1
Hostname: ams-box1 
Memory: 16384 MiB 
CPU Cores: 8 core(s))
Kernel: latest
State: running
```

Prepare it for Debian Buster, PG 11, connect an SSD volume, configure netfilter & co, transfer data from HKG/AMSdb, benchmark the host.

**Comment by hellais** [comment]
Related to: https://github.com/ooni/backend/issues/263

**Comment by hellais** [comment]
Also related: https://github.com/ooni/backend/issues/340

**Comment by hellais** [comment]
Todo LIST: https://github.com/ooni/backend/issues/263#issuecomment-617239785

**Comment by FedericoCeratto** [comment]
TODO:
- [ ] Setup new AMS db
- [ ] Rsync live datadir from HKG on temporary additional disk volume
- [ ] Try pg_upgrade
- [ ] Test API and fastpath against new AMS db
- [ ] Rsync datadir again from HKG while stopped
- [ ] Run pg_upgrade again
- [ ] Test API and fastpath against new AMS db


https://github.com/ooni/sysadmin/blob/master/docs/lvextend.md

**Comment by FedericoCeratto** [comment]
Blocked by host not booting

**Comment by hellais** [comment]
I started copying the /srv/ directory of hkgmetadb over to a AWS host and we can make an attemp there at doing pg_upgrade.

**Comment by hellais** [comment]
Beyond setting up a toy DB instance to test the upgrade procedure on AWS we were not able to move forward with this as we are still waiting on the folks from the eclips.is platform to get back to us about some issues we are having with attaching disks to the AMS host.

**Comment by hellais** [comment]
I documented what I did in order to upgrade from pg9 to 12 on the AWS host here: https://github.com/ooni/sysadmin/blob/master/docs/pg-upgrade.md.

**Comment by hellais** [comment]
Following a discussion with @FedericoCeratto we concluded that it might be better to go about doing a `pg_dump` and restore, to avoid having to copy the data dir around many times.

@FedericoCeratto ran a pg_dump yesterday and it took almost 4 hours, producing 733GiB. I think this is a clear sign that this is a very solid way forward.

**Comment by hellais** [comment]
Progress was made on this in the sprint, yet we discovered that in reality the backup and restore will take close to 9-10h to complete, instead of what we previously estimated.

Moreover the speed improvement of deploying to the new host is not substantial and actually we ran into issues when running both instances at the same time.

See: https://pad.riseup.net/p/ooni-database-migration-keep
