### ISSUE TITLE
Improve SSH connection handling in fastpath

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#404]
- [ ] test SSH connection loss
- [ ] monitor prod instance for SSH lockup
- [ ] test/improve grafana alerting

**Comment by FedericoCeratto** [comment]
https://github.com/ooni/pipeline/pull/318

**Comment by hellais** [comment]
The PR was merged, should we close this issue?

**Comment by FedericoCeratto** [comment]
Closing
