### ISSUE TITLE
API aggregation: handle category_code as an axis

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#409]
Handle queries like:
https://api.ooni.io/api/v1/aggregation?probe_cc=DE&since=2020-01-01&until=2020-01-02&axis_x=category_code
Add functional tests.

Related to https://github.com/ooni/backend/issues/402

**Comment by hellais** [comment]
Isn't this a duplicate of https://github.com/ooni/backend/issues/414?

**Comment by FedericoCeratto** [comment]
https://github.com/ooni/api/pull/189 was merged
TODO: deploy and test

**Comment by FedericoCeratto** [comment]
Deployed as 20200522-5ed8b180

Works -> https://api.ooni.io/api/v1/aggregation?probe_cc=DE&since=2020-01-01&until=2020-01-02&axis_x=category_code
