### ISSUE TITLE
Improve performance on counters table

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#411]
Queries slowed down despite the BRIN index. A BTREE has been added but it's not always used.
This will impact the db when the aggregation API is used by Explorer: Investigate further speedups.

**Comment by FedericoCeratto** [comment]
Notes at https://pad.riseup.net/p/ooni-counters-performance-ainohngiev5sheiWa9ro-keep

**Comment by hellais** [comment]
Is there something specific I should be doing to move this issue forward?

**Comment by hellais** [comment]
From what I gather by looking at the pad which you linked above, the BRIN index was not doing any good to that particular query and was actually making it significantly slower.

When you dropped the BRIN index, then it appears to be doing significantly better.

What was the original reason to add such an index? Does it perform well without the BRIN index also when other `probe_cc` are filtered?

I am not really sure how I can contribute to this issue beyond just asking some simple questions like there. I am going to un-assign myself from this issue.

If there is some specific aspect you would like me to look into, feel free to tag me in here with a comment.

**Comment by hellais** [comment]
@FedericoCeratto will update this with information on what was done and create a follow up issue with next steps.

**Comment by FedericoCeratto** [comment]
Update: we did not find the root cause for the different behavior between HKG and AMSdb. We'll check if AMSdb starts using the BTREE and BRIN indexes correctly either a reboot (required the disk size increase) or after moving to the new database.
