### ISSUE TITLE
Add blockpage fingerprints from citizenlab to fastpath

### ISSUE THREAD

**Issue by hellais** [ooni/backend#412]
We should look into adding these fingerprints to the fastpath detection logic: https://github.com/citizenlab/filtering-annotations/blob/master/analysislib/known_blockpages.py

**Comment by FedericoCeratto** [comment]
Update: Jakub is updating the repository to provide fingerprints as JSON files.

**Comment by hellais** [comment]
I migrated the DNS fingeprints to a separate issue: https://github.com/ooni/backend/issues/518 so we can close this within this sprint.

**Comment by hellais** [comment]
This is the script I used for generating the known_blockpages to add to our repo: https://gist.github.com/hellais/82a29b08a42f9e452966553afbe9010b

**Comment by hellais** [comment]
This is done.
