### ISSUE TITLE
URL prioritization backend: test

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#418]
Next step for https://github.com/ooni/backend/issues/361
TODO:
- [x] configure local Nginx to serve files based on query
- [x] implement fallback to static files if the backend stops updating the dynamic files
- [x] switch traffic from orchestration nginx

**Comment by hellais** [comment]
This is the nginx config for the probe-services: https://github.com/ooni/sysadmin/blob/master/ansible/roles/probe-services/templates/probe-services-nginx

**Comment by FedericoCeratto** [comment]
The nginx on ams-ps2 is receiving GETs for `/api/v1/test-list/urls?category_codes=....&limit=17&probe_cc=...` that should be redirected to the new service.

**Comment by FedericoCeratto** [comment]
Related https://github.com/ooni/pipeline/pull/321

**Comment by FedericoCeratto** [comment]
New grafana dashboard created

**Comment by FedericoCeratto** [comment]
All done
