### ISSUE TITLE
Create domain names: ps{1,2,3}.ooni.io

### ISSUE THREAD

**Issue by bassosimone** [ooni/backend#424]
This is about creating new domain names `ps{1,2,3}.ooni.io` and letting me know such that I can use them inside of the ooni/probe-engine repository. (@hellais I'm adding you and I am adding the next sprint to make sure this issue is visible to someone, please route it as needed.)

**Comment by hellais** [comment]
I have added 4 new domains for the probe services here: https://github.com/ooni/sysadmin/commit/d527cb5616baa37da06620eee1ed3feabcc13fef

ps1.ooni.io -> ams-ps2.ooni.nu
ps2.ooni.io -> mia-ps2.ooni.nu
ps3.ooni.io -> hkg-ps.ooni.nu
ps4.ooni.io -> ams-ps.ooni.nu (ps.ooni.io)

I am now deploying the changes as DNS propagates and we get the new certificates that include those alt names as well.

I will update this issue when that is done.

Once it's deployed, it would be great if you could do some testing of them to ensure everything is working as expected. Especially the endpoints related to orchestrate and the bouncer, which have until now been running on ams-ps.ooni.nu and I don't think we ever tried using the other hosts for it.

**Comment by bassosimone** [comment]
Sure thing! Thank you!

**Comment by hellais** [comment]
The deployment has been run. This is implemented.

**Comment by bassosimone** [comment]
Follow-up https://github.com/ooni/probe-engine/issues/686
