### ISSUE TITLE
Implement Probe Service blocking detection: basic prototype

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#428]
Implement basic prototype, generate metrics and grafana dashboard and review it after 2w.

**Comment by FedericoCeratto** [comment]
A simple script is running on ams-ps2 and producing:
https://mon.ooni.nu/grafana/d/5s3NppiMk/probe-services-access?tab=queries&panelId=2&edit&fullscreen&orgId=1&from=1591699123618&to=now - we'll wait few days to generate some useful metrics and discuss next steps

**Comment by FedericoCeratto** [comment]
Added grouping by CC and by report open VS close action

**Comment by bassosimone** [comment]
Assigned also myself to this issue because I am providing a little help to move this forward. So, it's better if this issue is clearly part of my radar rather than not.

**Comment by bassosimone** [comment]
We discussed with @FedericoCeratto that we could run this natural experiment. Collect data for a period of time, then turn on selection of the fastest probe-services instance. This would show us wha happens when users stop using a specific instance of the probe-services.

**Comment by hellais** [comment]
We have done manual parsing of the logs and concluded that no blocking is currently happening.

Perhaps we should eventually make this prototype something that runs in production, but for the moment this is to be considered done.
