### ISSUE TITLE
Add API to return the URLs used by the prio backend with the associated priority

### ISSUE THREAD

**Issue by hellais** [ooni/backend#429]
This is about having an endpoint which can be queries that will return all the URLs being used by the prioritization backend with relevant metadata.

Example response:
```
{
"urls": [{
"url": "https://example.com",
"priority": 2,
"category_code": "TEST",
"country_code": "IT"
}]
}
```

**Comment by FedericoCeratto** [comment]
Implemented in https://github.com/ooni/api/pull/192

**Comment by hellais** [comment]
The API endpoint: https://orchestrate.ooni.io/api/v1/test-list/urls?country_code=IT, does not return the priority of the URLs.

**Comment by FedericoCeratto** [comment]
Superseded by #495
