### ISSUE TITLE
Empty collector is treated as a failure by the batch pipeline

### ISSUE THREAD

**Issue by hellais** [ooni/backend#434]
Currently the batch pipeline treats an empty collector during the `collector_sensor_XX` task as a failure. This leads to confusing alerts inside of #ooni-bots.

In particular this is the case with ams-ps.ooni.nu, which was used at some point to submit measurements to, but now we switched to not using it anymore.

I think the optimal solution would be to change the behaviour of the batch pipeline to consider an empty collector as an OK result, but maybe in the interim, we can either silence the alert or if @bassosimone thinks no more measurements should be submitted there, just disabling scraping it.

**Comment by FedericoCeratto** [comment]
Obsoleted by https://github.com/ooni/backend/issues/437
