### ISSUE TITLE
Investigate missing NDT measurements

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#436]
http://api.ooni.io/api/v1/measurements?report_id=20200717T115043Z_AS262352_i71SGKYMNllRJ2gF9psZt65BEKCWN8CeSkqERwI8rEd4tMBcJc returns a msmt

https://api.ooni.io/api/v1/measurement/temp-fid-00d814ed0d58e99d37f44a036315236d is not finding it

`select * from fastpath where report_id = '00d814ed0d58e99d37f44a036315236d'` indicates that the msmt is missing

While chasing it, add CC/test_name filters to fastpath to rerun it quickly.

**Comment by hellais** [comment]
This measurement now appears to exist and the retrieval URL is working as expected.

I suppose we can close this issue at this point.
