### ISSUE TITLE
Implement fastpath-based API to support explorer

### ISSUE THREAD

**Issue by hellais** [ooni/backend#442]
This involves implementing enough of the private API using the counters or fastpath related tables so that we can rely entirely on the new tables and fully support OONI Explorer.

This might also require some OONI Explorer side related changes in order to achieve this.

**Comment by FedericoCeratto** [comment]
Implemented in https://github.com/ooni/api/pull/192

**Comment by bassosimone** [comment]
I am going to close this issue because we're using the large list at https://github.com/ooni/backend/issues/437 for tracking all the work done as part of implementing the new API. As such, I find this issue confusing.
