### ISSUE TITLE
Get support from postgres expert

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#445]
We urgently need a postgresDBA expert to help us. We can find a list of services from the Postgres website: https://www.postgresql.org/support/professional_support/europe/ & https://www.credativ.com/postgresql-competence-center

**Comment by agrabeli** [comment]
@hellais you mentioned that there might be someone who you could reach out to. Is that still the case?

**Comment by bassosimone** [comment]
@FedericoCeratto says this is not a priority for this sprint, so we'll re-evaluate in the next Sprint.
