### ISSUE TITLE
QA and e2etesting for refactored API

### ISSUE THREAD

**Issue by bassosimone** [ooni/backend#446]
- [x] `ooni/probe-engine` can use the refactored API
- [x] `measurement-kit/measurement-kit` can use the refactored API
- [x] `ooni/probe-legacy` can use the refactored API
- [x] probe-engine: use ams-pg.ooni.org in tests
- [x] measurement-kit: use ams-pg.ooni.org in tests
- [x] github.com/ooni/e2etesting
- [x] e2etesting: separate runners for more fine grained control and reporting
- [x] implement round-trip testing where we fetch back the measurement we submitted
- [x] <strike>probe-legacy: use ams-pg.ooni.org in tests</strike> (we're not working on this)
- [x] document future improvements
- [x] remember revert changes to integration tests once we're confident
- [x] e2etesting: further refine testing environments

(Each point in the above TODO list is further expanded below in separate comments.)

**Comment by bassosimone** [comment]
## QA for ooni/probe-engine

We spotted this problem when we started using `ams-pg.ooni.org` with `miniooni`:

```
[    131.111568] <warn> submitting measurement failed: map[error:httpx: request failed: 500 Internal Server Error]
```

This problem has been fixed. It is honestly unclear to me how :-). After this problem has been fixed, we start a submit loop with `miniooni`, which should allow us to understand whether everything is as WAI as it seems.

**Comment by bassosimone** [comment]
## QA for measurement-kit

The first time we tried running MK against the refactored API, we saw:

```
% measurement_kit -A manyooni_mk=-1 --bouncer https://ams-pg.ooni.org -v web_connectivity -u http://x.org
Contacting bouncer: https://ams-pg.ooni.org
[D] resolve_hostname: ams-pg.ooni.org
[D] resolve_hostname: ipv4...
[D] getaddrinfo('ams-pg.ooni.org') => error: code=0, reason=''
[D] resolve_hostname: ipv4... done
[D] resolve_hostname: ipv6...
[D] getaddrinfo('ams-pg.ooni.org') => error: code=0, reason=''
[D] resolve_hostname: ipv6... done
[D] connect_base 142.93.237.101:443
[D] connect() in progress...
[D] connect time: 0.045268
[D] ssl: creating SSL_CTX with bundle: '/etc/ssl/cert.pem'
[D] SSL version: TLSv1.3
[D] ssl: handshake...
[D] ssl: handshake... complete
[D] > POST /bouncer/net-tests HTTP/1.1
[D] > Content-Type: application/json
[D] > Host: ams-pg.ooni.org
[D] > Content-Length: 117
[D] >
[D] http: started reading response
[D] http: passing read data to parser
[D] < HTTP/1.1 500 INTERNAL SERVER ERROR
[D] < Server: nginx/1.14.2
[D] < Date: Fri, 11 Sep 2020 15:39:56 GMT
[D] < Content-Type: application/json
[D] < Content-Length: 90
[D] < Connection: keep-alive
[D] < Access-Control-Allow-Origin: *
[D] < X-RateLimit-Remaining: 398
[D] <
[D] http: received error 0 on connection
[!] bouncer parsing error: json_processing_error
95%: ending the test
100%: test complete
Overall data usage (bytes): 415 down - 284 up
```

We implemented `/bouncer/net-tests` to return the following:

```JSON
{
  "net-tests": [
    {
      "collector-alternate": [
        {
          "type": "https",
          "address": "https://ams-pg.ooni.nu"
        },
        {
          "front": "dkyhjv0wpi2dk.cloudfront.net",
          "type": "cloudfront",
          "address": "https://dkyhjv0wpi2dk.cloudfront.net"
        }
      ],
      "version": "$input_version",
      "name": "$input_name",
      "test-helpers": {
        "tcp-echo": "37.218.241.93",
        "http-return-json-headers": "http://37.218.241.94:80",
        "web-connectivity": "httpo://y3zq5fwelrzkkv3s.onion"
      },
      "test-helpers-alternate": {
        "web-connectivity": [
          {
            "type": "https",
            "address": "https://wcth.ooni.io"
          },
          {
            "front": "d33d1gs9kpq1c5.cloudfront.net",
            "type": "cloudfront",
            "address": "https://d33d1gs9kpq1c5.cloudfront.net"
          }
        ]
      },
      "collector": "httpo://jehhrikjjqrlpufu.onion",
      "input-hashes": null
    }
  ]
}
```

This is not what the original backend would do. It is, in fact, a superset object addressing all possible requests. We only need to copy into the output `name` and `version` by using the fields from the request.

While investigating this issue, we also discovered that TLSv1.3 settings were too restrictive:

```
% curl -v https://ams-pg.ooni.org/bouncer/net-tests                                                      
*   Trying 142.93.237.101...
* TCP_NODELAY set
* Connected to ams-pg.ooni.org (142.93.237.101) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS alert, protocol version (582):
* error:1400442E:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert protocol version
* Closing connection 0
curl: (35) error:1400442E:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert protocol version
```

This failure is from macOS using cURL, where TLSv1.3 is disabled. This should have been fixed by now and is very relevant for the legacy probes and for Lepidopter, which were mainly using typically Wheezy and Jessie.

Once all of this was fixed we had this additional issue:

```
[D] < HTTP/1.1 413 Request Entity Too Large
[D] < Server: nginx/1.14.2
[D] < Date: Fri, 11 Sep 2020 18:13:40 GMT
[D] < Content-Type: text/html
[D] < Content-Length: 199
[D] < Connection: close
[D] <
[D] http: BODY
[D] http: END
[D] <html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
```

Which has been solved by making the maximum POST data size larger. After that, we were able to run in a loop MK submissions using:

```bash
#!/bin/bash
set -x
debug=
idx=0
while [ true ]; do
  $debug measurement_kit -A "manyooni=mk_${idx}"  \
    --bouncer https://ams-pg.ooni.org             \
    web_connectivity -u http://mail.google.com/
  idx=$(($idx + 1))
  sleep 44
done
```

**Comment by bassosimone** [comment]
## QA for ooni/probe-legacy

The first attempt failed like this:

```
 % ooniprobe -v -P https --bouncer=https://ams-pg.ooni.org/ web_connectivity -u https://x.org
No test deck detected
Checking if backend is present
Checking if dns-discovery is present
[!] Error processing dns_spoof.py
[!] Error processing traceroute.py
Tor is not running. Skipping IP lookup via Tor.
Looking up your IP address via ubuntu
Found your IP via a GeoIP service
Running task update-inputs
Did not run update-inputs
Looking up collector and test helpers with https://ams-pg.ooni.org
Querying backend https://ams-pg.ooni.org/bouncer/net-tests with {'net-tests': [{'test-helpers': ['web-connectivity'], 'version': '0.3.2', 'name': 'web_connectivity', 'input-hashes': []}]}
Got this backend error message {u'error': u"'dict' object is not callable\\nThe view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a dict."}
```

This first error was caused by some code injecting `error` in the scope.

A second problem we discovered is the following:

```
Looking up collector and test helpers with https://ams-pg.ooni.org
Querying backend https://ams-pg.ooni.org/bouncer/net-tests with {'net-tests': [{'test-helpers': ['web-connectivity'], 'version': '0.3.2', 'name': 'web_connectivity', 'input-hashes': []}]}
Got this backend error message {u'error': u'JSON expected'}
Unhandled Error
```

This was more puzzling but in the end we realised the issue was that `POST /bouncer/net-tests` did not set the `Content-Type` header when run from `ooni/probe-legacy`. We implemented a workaround.

Past this phase, we had this mysterious error:

```
Looking up collector and test helpers with https://ams-pg.ooni.org
Querying backend https://ams-pg.ooni.org/bouncer/net-tests with {'net-tests': [{'test-helpers': ['web-connectivity'], 'version': '0.3.2', 'name': 'web_connectivity', 'input-hashes': []}]}
Querying backend https://ams-pg.ooni.org/invalidpath with None
[!] Could not start the director
[!] An unhandled exception occurred while starting the director!
Unhandled Error
Traceback (most recent call last):
Failure: ooni.errors.OONIBError: 
```

This issue is caused by `ooni/backend_client.py`: the `genReceiver` function assumes that either there is no body or, if there is a body, then it oughta be a JSON. So we fixed the backend to return a JSON.

After fixing that we made some progress, but still we weren't successful:

```
Querying backend https://ams-pg.ooni.org/report with {'data_format_version': '0.2.0', 'software_name': 'ooniprobe', 'test_version': '0.3.2', 'software_version': '2.3.0', 'test_name': 'web_connectivity', 'test_start_time': '2020-09-16 09:35:40', 'format': 'json', 'input_hashes': [], 'probe_asn': 'AS30722', 'probe_cc': 'IT'}
Got this backend error message {u'error': u'JSON expected'}
[!] Failed to connect to reporter backend
```

This issue seems to be similar to the previous issue where the `Content-Type` was missing. But now this is occurring to another URL, the one for opening a new report.

**We are currently stuck trying to fix this problem**.

**Comment by bassosimone** [comment]
In https://github.com/ooni/probe-engine/pull/942 I have switched ooni/probe-engine to use ams-pg.ooni.org for the QA.

**Comment by bassosimone** [comment]
In https://github.com/measurement-kit/measurement-kit/pull/1932 I did the same for MK.

**Comment by bassosimone** [comment]
## github.com/ooni/e2etesting

Repository where we periodically run current and legacy probes to check whether we can run, submit and then fetch measurements using the refactored APIs deployed at https://ams-pg.ooni.org. As of https://github.com/ooni/e2etesting/commit/105849eec36cb56308ce4cd4ef5826e59c8aedcb, we're doing reasonably good but we have this issue that we're using a legacy probe in a modern environment. We would instead like to run the legacy probe in a debian7 (or debian8?) environment, which is more close to what we had in Lepidopter.

**Comment by bassosimone** [comment]
## Further improvements

* https://github.com/ooni/e2etesting/pull/8

* https://github.com/ooni/e2etesting/pull/9

**Comment by bassosimone** [comment]
## probe-legacy: use ams-pg.ooni.org in tests

I chose not to work on implementing this functionality. The software is rather legacy and I'd rather spend some more time trying to ensure the lepidopter-like environment is as equal to lepitoper as possible.

**Comment by bassosimone** [comment]
## document future improvements

* https://github.com/ooni/probe-engine/issues/948

**Comment by bassosimone** [comment]
##  remember revert changes to integration tests once we're confident

* https://github.com/ooni/probe-engine/issues/949

* https://github.com/measurement-kit/measurement-kit/issues/1933

**Comment by bassosimone** [comment]
## e2etesting: further refine the debian8 environment for lepidopter

We need to understand what version of versions of ooni/probe-legacy we should be testing. We need to understand how the lepidopter updater works and the impact that this has on the dependencies version.

Let us the following table generated today and showing the most frequent softwares running tests:

software_name     | software_version | count   | percentage |
----------------- | ---------------- | ------- | ---------- |
measurement_kit   | 0.7.1            | 1235088 | 34.554102  |
measurement_kit   | 0.9.0-alpha.2    | 708797  | 19.830040  |
measurement_kit   | 0.10.1           | 348581  | 9.752263   |
ooniprobe-android | 2.2.0            | 142096  | 3.975425   |
ooniprobe-android | 2.3.2            | 111921  | 3.131218   |
ooniprobe         | 2.1.0            | 107776  | 3.015253   |
measurement_kit   | 0.8.1            | 86986   | 2.433610   |
ooniprobe-android | 2.4.0            | 85567   | 2.393911   |
measurement_kit   | 0.9.0-dev        | 81560   | 2.281807   |
ooniprobe         | 2.2.0            | 71012   | 1.986705   |
ooniprobe         | 2.3.0            | 61502   | 1.720644   |
ooniprobe-android | 2.5.2            | 61002   | 1.706655   |
ooniprobe-android | 2.5.0            | 46848   | 1.310668   |
ooniprobe-android | 2.3.1            | 42139   | 1.178924   |
ooniprobe-android | 2.5.1            | 33176   | 0.928166   |

The table sums about 90% of the tests run in the last 30 days.

**Comment by bassosimone** [comment]
Created potential follow-up issue. We can close this issue now.

**Comment by bassosimone** [comment]
Forgot to mention this issue was in the context of https://github.com/ooni/backend/issues/437.

**Comment by MGNMTECHbuzz** [comment]
> * [x]  `ooni/probe-engine` can use the refactored API
> * [x]  `measurement-kit/measurement-kit` can use the refactored API
> * [x]  `ooni/probe-legacy` can use the refactored API
> * [x]  probe-engine: use ams-pg.ooni.org in tests
> * [x]  measurement-kit: use ams-pg.ooni.org in tests
> * [x]  github.com/ooni/e2etesting
> * [x]  e2etesting: separate runners for more fine grained control and reporting
> * [x]  implement round-trip testing where we fetch back the measurement we submitted
> * [x]  probe-legacy: use ams-pg.ooni.org in tests (we're not working on this)
> * [x]  document future improvements
> * [x]  remember revert changes to integration tests once we're confident
> * [x]  e2etesting: further refine testing environments
> 
> (Each point in the above TODO list is further expanded below in separate comments.)

Sorry new and looking for a little helpful answers to a couple specific questions on api and android device code editors or anything else running from Android device dannyvega233@gmail.com
