### ISSUE TITLE
mobile: periodic testing of refactored API

### ISSUE THREAD

**Issue by bassosimone** [ooni/backend#450]
[This issue is in the backend repository because the work done on mobile as part of it will benefit the backend. My initial effort estimate is XL because there is a bunch of coordination between me and @lorenzoPrimi to make this happen.]

We want to have automatically running GitHub Actions that run every ~4 hours and ensure that the currently in-use versions of ooni/probe-android and ooni/probe-ios work with the ams-pg.ooni.org API.

This issue calls for making sure we have the following integration tests:

- [x] Web Connectivity runs with ams-pg.ooni.org as probe services URL
- [x] we can fetch the test lists from ams-pg.ooni.org
- [x] we can check whether a measurement exists using ams-pg.ooni.org
- [ ] (optional) whether Web Connectivity and later retrieve its measurements

We likely want to run this test for versions 2.5.2, 2.5.3, and master of both apps. We want to test whether the code continues to work as well as whether the dependencies a previous version may have been using are still working.

Coverage across both apps is more important than going in depth for a single app. Yet, Android is more important than iOS because we have more users on Android. So, more complex integration tests should be implemented for Android first.

Once we have switched to the refactored API, we should keep this automatic test mechanism just for master, albeit with a much larger interval between runs. Ideally, running the whole test suite at least weekly seems a good target.

**Comment by lorenzoPrimi** [comment]
preTODO:
1) include `ams-pg.ooni.org` as a parameter in the app
2) let all the api calls (get urls, get measurement) use a parameterized url instead of a fixed one

Doubts:
- How to tell web connectivity to use another probe service url? @bassosimone

**Comment by bassosimone** [comment]
> How to tell web connectivity to use another probe service url? @bassosimone

if the test is written in MK `bouncer_base_url` inside of `options`. Otherwise `probe_services_base_url` inside of `options`.

**Comment by lorenzoPrimi** [comment]
The
 ```
we can fetch the test lists from ams-pg.ooni.org
 we can check whether a measurement exists using ams-pg.ooni.org
```


unit test already exist, we just need to edit the url, do we want to add it in the app? like as variable? 
or create a branch editing these
```
  public static final String OONI_API_BASE_URL = "https://api.ooni.io/";
  public static final String OONI_ORCHESTRATE_BASE_URL = "https://orchestrate.ooni.io/";
```
as `ams-pg.ooni.org`, just to run tests?

**Comment by bassosimone** [comment]
@lorenzoPrimi I suggest that we have a part of the code where we can pass in the base URL as an argument. Then, in the app we will use the constants like `OONI_API_BASE_URL`, while in the tests we use the `ams-pg` URL.

**Comment by lorenzoPrimi** [comment]
A branch based on `v2.6.0` has been created adding the new integration tests:
https://github.com/ooni/probe-android/tree/stable

**Comment by bassosimone** [comment]
Reopening because we've not implemented iOS. I'll work on this later today or tomorrow.

**Comment by bassosimone** [comment]
iOS done here: https://github.com/ooni/probe-ios/pull/390#event-3851948913
