### ISSUE TITLE
riseupvpn: add to API and Explorer

### ISSUE THREAD

**Issue by cyBerta** [ooni/backend#473]
After an experiment to test the availability of RiseupVPN has been added to probe-engine, we need ways to fetch the data from the API. 
I had a look here: https://api.ooni.io/apidocs/#/default/get_api_v1_measurements  and it seemed to be the proper endpoint to add a new 'riseupvpn' test_name value there. 

I'm not sure if there are already other ways to fetch the required data.

**Comment by bassosimone** [comment]
It seems there's nothing to do on the Explorer side. Since every meaningful change has been implemented on the API side already. See https://explorer.ooni.org/search?until=2020-11-12&since=2020-10-12.

**Comment by bassosimone** [comment]
Reopening because the measurement page cannot load the measurement: https://explorer.ooni.org/measurement/20201111T190355Z_riseupvpn_IT_30722_n1_4yj98WBm5ECsKI5g.

**Comment by bassosimone** [comment]
I've implemented an initial algorithm for scoring riseupvpn measurements here: https://github.com/ooni/explorer/pull/522

**Comment by bassosimone** [comment]
@cyberta: it's now possible to see riseupvpn measurements on Explorer, so I feel like we can close this issue and chat on IRC about further steps!

**Comment by cyBerta** [comment]
Thanks @bassosimone and @FedericoCeratto for your fast work!
