### ISSUE TITLE
api: add support for experimental test group

### ISSUE THREAD

**Issue by hellais** [ooni/backend#484]
Currently when you lookup an experimental test in the API you get an error, see: https://api.ooni.io/api/v1/raw_measurement?report_id=20210311T112951Z_signal_IT_30722_n1_EN139Po0v5W7oOcq.

It should return instead the raw measurement data.

Related: https://github.com/ooni/probe/issues/1390

**Comment by FedericoCeratto** [comment]
Added signal and stunreachability to the database, reran fastpath from 2021-3-9 to 2021-3-12
