### ISSUE TITLE
Add social media URLs for top URL prioritization

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#507]
Social media URLs are frequently blocked around the world, particularly during political events. Read more about the problem here: https://github.com/ooni/probe/issues/1412

Following a team discussion, we decided to **add some of the most popular (and frequently blocked) social media websites to the top of URL prioritization** (so that they get tested every time an OONI Probe user runs OONI Probe -- either manually, or via automated testing). 

Once popular social media URLs have been prioritized for testing for a few weeks, we will analyze OONI data to evaluate how effective this approach is in ensuring that popular social media websites receive sufficient testing coverage around the world (particularly in countries where they're blocked). 

@FedericoCeratto please add the following social media websites to the top of URL prioritization (i.e. highest URL priority):

```
https://www.facebook.com/
https://twitter.com/
https://www.instagram.com/
https://www.whatsapp.com/
https://web.whatsapp.com/
https://telegram.org/
https://web.telegram.org/
https://www.youtube.com/
https://www.tiktok.com/
https://www.viber.com/
https://www.snapchat.com/
https://www.reddit.com/
https://vimeo.com/
https://www.wechat.com/
https://international.qq.com/
https://signal.org/
```

**Comment by hellais** [comment]
This will be done once we switch the UI to using the production backend.

**Comment by FedericoCeratto** [comment]
Done

**Comment by FedericoCeratto** [comment]
Updated to match URLs instead of domain
