### ISSUE TITLE
test-list: prevent cannot-verify-email-origin warning from gmail

### ISSUE THREAD

**Issue by bassosimone** [ooni/backend#524]
This is the email I received from the contact@ooni.org when I registered to the test-list system:

<img width="532" alt="Screenshot 2021-07-27 at 16 08 48" src="https://user-images.githubusercontent.com/337298/127171219-eecff3b1-54b7-422e-a5a9-f0308d03cbee.png">

Hovering on the question mark it roughly says "gmail could not verify whether this is sent from ooni.org (it may also be spam)".

It seems we might fix this by adding an SPF record to ooni.org: https://support.google.com/mail/answer/180707#:~:text=If%20you%20see%20a%20question,replying%20or%20downloading%20any%20attachments

**Comment by hellais** [comment]
I have now configured the spf record for the domain appropriately to be:
```
ooni.org.		1798	IN	TXT	"v=spf1 include:_spf.google.com include:riseup.net ~all"
```

It passes the spf validation now:
```
Received-SPF: pass (google.com: domain of contact@ooni.org designates 198.252.153.129 as permitted sender) client-ip=198.252.153.129;
```
