### ISSUE TITLE
De-prioritize the testing of risky website categories in Afghanistan

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#530]
During the August 2021 OONI Community Meeting, a community member highlighted that testing some of the more obviously risky website categories in Afghanistan may present an increased risk for OONI Probe users in the country (in light of recent events). 

They therefore highlighted the need to review the test list for Afghanistan (https://github.com/citizenlab/test-lists/blob/master/lists/af.csv) and consult with a local expert (on potential risks).

As a sort of short term "solution" for safety, we discussed that perhaps **OONI could de-prioritize the testing of website categories that are more obviously risky** (such as gambling, alcohol, pornography, militant, etc.)  in Afghanistan. 

@FedericoCeratto Does it make sense to de-prioritize categories, or should we instead boost the prioritization of other categories (e.g. news media)? 

For reference, here are the Citizen Lab website categories: https://github.com/citizenlab/test-lists/blob/master/lists/00-LEGEND-new_category_codes.csv

If possible, perhaps we could start off by de-prioritizing the following categories in Afghanistan (mainly from the **Global test list**): `ALDR`, `PORN`, `PROV`, `MILX`, `HATE`, `GMB`.

Thoughts?

**Comment by FedericoCeratto** [comment]
"banning" a whole category will be possible once https://github.com/ooni/api/pull/264 is deployed.

**Comment by FedericoCeratto** [comment]
Feature deployed, rules added.

**Comment by agrabeli** [comment]
Thank you @FedericoCeratto !

**Comment by xhdix** [comment]
I asked someone more familiar with Afghanistan to look at this issue and comment. A few more items may need to be banned until further notice. (e.g., `LGBT`)
I ask her to join OONI Community on Slack: https://slack.ooni.org/

**Comment by xhdix** [comment]
She said:

Dangerous: `ALDR`,  `PORN`, `PROV`, `MILX`, `XED`, `GMB`, `DATE`, `LGBT`
Risky:  `HUMR`, `HATE`

**Comment by agrabeli** [comment]
Thank you @xhdix !

@FedericoCeratto can we de-prioritize the above categories in Afghanistan?

**Comment by FedericoCeratto** [comment]
As now the following categories are completely **disabled** in Afghanistan: LGBT XED ALDR GMB HATE MILX PROV PORN

**Comment by xhdix** [comment]
Can you disable `DATE` and `LGBT` too? And if it's possible de-prioritize `HUMR` and `HATE` for now?

**Comment by hellais** [comment]
Sorry for updating this issue so late, but as of now the following categories are de-prioritised:
```
PORN	AF	*	*	-9999
PROV	AF	*	*	-9999
MILX	AF	*	*	-9999
HATE	AF	*	*	-9999
GMB	AF	*	*	-9999
ALDR	AF	*	*	-9999
XED	AF	*	*	-9999
LGBT	AF	*	*	-9999
DATE	AF	*	*	-9999
```
