### ISSUE TITLE
Add DNS fingerprints for Iran

### ISSUE THREAD

**Issue by hellais** [ooni/backend#543]
It has been reported that we should add to the fingerprint database the following IPs for country level censorship in Iran:
```
d0::11
10.10.34.36
```

Some reference measurements are:
* https://explorer.ooni.org/measurement/20210701T022229Z_webconnectivity_IR_197207_n1_1gpWGw5V9YWvEa44?input=http%3A%2F%2Fwww.freeexpression.org%2F
* https://explorer.ooni.org/measurement/20210715T094141Z_webconnectivity_IR_44244_n1_GFBhOu2puPdz4SSt?input=https%3A%2F%2Fwww.sbs.com.au%2Flanguage%2Fcoronavirus%3Fcid%3Dinfocus

**Comment by FedericoCeratto** [comment]
0.59~pr395-152 deployed on FSN

**Comment by FedericoCeratto** [comment]
https://explorer.ooni.org/measurement/20220815T190043Z_webconnectivity_IR_197207_n1_cCbffjGasS4tFgb2?input=https%3A%2F%2Fwww.facebook.com%2F has been fingerprinted as:
```scores:                 {"blocking_general":1.0,"blocking_global":0.0,"blocking_country":0.0,"blocking_isp":0.0,"blocking_local":0.0,"analysis":{"blocking_type":"dns"}}```
