### ISSUE TITLE
wcth: deploy and use new implementation

### ISSUE THREAD

**Issue by bassosimone** [ooni/backend#544]
This issue is about deploying the new wcth implementation. (If everything is okay with respect to automatic deployment, it should already be there, actually.) When we're sure about this, we should replace the old test helper.

**Comment by bassosimone** [comment]
With @FedericoCeratto we're going to start an incremental rollout where just a few ASNs will use the new TH. We will monitor the new TH load and the results.

**Comment by hellais** [comment]
@bassosimone says that the new test helper has been tested fully and we are good to start the rollout into production.

We should go ahead with re-routing some percentage of production traffic over to the new test helper. @FedericoCeratto look into this.

Once we have determined that the new test helper can handle the load, we are going to rollover everything to it.

**Comment by hellais** [comment]
In looking into https://github.com/ooni/probe/issues/2050 we noticed that the new test helper does not timeout when accessing www.tiktok.com. We should bump up the priority of the deployment of the wcth, because it's having an impact on data quality.

**Comment by FedericoCeratto** [comment]
A fraction of the probes has been directed to the new test helpers.
There's also a dedicated dashboard https://grafana.ooni.org/d/Dn1R7QEnz/new-test-helpers?orgId=1&from=now-30m&to=now

**Comment by bassosimone** [comment]
I think we can optimistically say we did this. If something goes very wrong we'll roll back, but all seems good so far.
