### ISSUE TITLE
whatsapp: score http://web.whatsapp.com results

### ISSUE THREAD

**Issue by bassosimone** [ooni/backend#546]
The current pipeline implementation does not score the result of http://web.whatsapp.com (see https://github.com/ooni/pipeline/blob/8779ad87914c5323688d8aeb500aac450fd1e0da/af/fastpath/fastpath/core.py#L778) and only uses https://web.whatsapp.com to compute whether there is blocking.

We would like to improve the algorithm by also looking at http://web.whatsapp.com to decide on web blocking.

The corresponding code in the probe for deciding whether there is a web failure is at https://github.com/ooni/probe-cli/blob/33de7012636bbfd68a7dfc9c9312a76b0c40354e/internal/engine/experiment/whatsapp/whatsapp.go#L104.

This is an example measurement: https://explorer.ooni.org/measurement/20211110T160846Z_whatsapp_IR_31549_n1_ysEHfCvhHjEj58JN

**Comment by bassosimone** [comment]
@hellais what is missing to complete this unit of work is just to add documentation to the function that performs header comparison. I've just added extensive documentation for the function, so I guess we can consider this done and move forward with merging. Thanks again for taking leadership here.

**Comment by hellais** [comment]
Excellent! Thanks for that. I am closing this issue.
