### ISSUE TITLE
Add support for scoring the stunreachability experiment

### ISSUE THREAD

**Issue by hellais** [ooni/backend#551]
This involves adding logic to the data processing pipeline so that it's able to score stunreachability experiments (see: https://github.com/ooni/spec/blob/master/nettests/ts-025-stun-reachability.md).

An MVP for the scoring logic, can involve simply looking at the value of the `failure` key to determine if a particular stun endpoint is reachable or not.

**Comment by FedericoCeratto** [comment]
Implemented in https://github.com/ooni/pipeline/pull/375

**Comment by hellais** [comment]
This has been implemented. Closing.
