### ISSUE TITLE
Test the new clickhouse based API and switch over to it

### ISSUE THREAD

**Issue by hellais** [ooni/backend#552]
This involves doing both manual and automated testing of the deployed clickhouse based API. Checking that everything works as expected and that it meets the desired performance.

Once this is done we will proceed to switching over to using that in production. In the first iteration we should only do that for OONI Explorer.

**Comment by FedericoCeratto** [comment]
As part of the preparation:
- [ ] Sync up fastpath table from prod
- [ ] Check and sync up jsonl table

**Comment by FedericoCeratto** [comment]
Done
