### ISSUE TITLE
Investigate why some control measurements fail (connection refused error)

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#560]
A number of measurements collected from Turkmenistan show that the control experiment failed (resulting in a `connection_refused` error), suggesting that they might be blocking our backend.

Relevant measurements include:
https://explorer.ooni.org/measurement/20211030T070225Z_webconnectivity_TM_20661_n1_a4Mmz4unMl2V9OAx?input=http%3A%2F%2Ffteproxy.org%2F 
https://explorer.ooni.org/measurement/20211030T070225Z_webconnectivity_TM_20661_n1_a4Mmz4unMl2V9OAx?input=https%3A%2F%2Fwww.rbc.ru%2F 
https://explorer.ooni.org/measurement/20211030T070225Z_webconnectivity_TM_20661_n1_a4Mmz4unMl2V9OAx?input=https%3A%2F%2Frus.azattyq.org%2F 

We should probably discuss this in our backend meeting and evaluate whether this is a systemic issue or not. 

We can probably explore this question by analyzing OONI data to evaluate:

- Percentage of measurements from TM that result in `connection_refused` error
- Percentage of global measurements that result in `connection_refused` error (to see if this is also a problem elsewhere)

This ticket will be closed once we have investigated this issue, determined the cause of these control failures, and fixed any potential bugs.

**Comment by hellais** [comment]
So much time has passed that we can't reliably look into this anymore. Closing it.
