### ISSUE TITLE
aggregation: the until field should be < instead of <=

### ISSUE THREAD

**Issue by hellais** [ooni/backend#572]
Currently the until field is applies as <= (see: https://github.com/ooni/api/blob/clickhouse/newapi/ooniapi/measurements.py#L1863), this means that if there are measurements matching the search criteria on exactly midnight of the until date, we will end up including them. This will result in having an additional date (the until date), in the GROUP BY clause.

We noticed this while debugging some issues in the MAT with @sarathms where we noticed that some category codes were returning an extra date compared to others.

**Comment by FedericoCeratto** [comment]
Fixed
