### ISSUE TITLE
api: stunreachability is not supported by list_measurements API

### ISSUE THREAD

**Issue by hellais** [ooni/backend#573]
When performing this query: https://backend-fsn.ooni.org/api/v1/measurements?test_name=stunreachability

You get the following error:
```
'stunreachability' is not one of ['bridge_reachability', 'dash', 'dns_consistency', 'dnscheck', 'facebook_messenger', 'http_header_field_manipulation', 'http_host', 'http_invalid_request_line', 'http_requests', 'meek_fronted_requests_test', 'multi_protocol_traceroute', 'ndt', 'psiphon', 'riseupvpn', 'signal', 'tcp_connect', 'telegram', 'tor', 'torsf', 'urlgetter', 'vanilla_tor', 'web_connectivity', 'whatsapp']
```

It's worth noting that the aggregation API endpoint works fine:
https://backend-fsn.ooni.org/api/v1/aggregation?test_name=stunreachability&axis_x=measurement_start_day&axis_y=probe_cc

**Comment by FedericoCeratto** [comment]
Fixed and deployed as part of https://github.com/ooni/api/pull/271
