### ISSUE TITLE
Tweak prioritization algorithm to ensure counts per ASN (instead of per country)

### ISSUE THREAD

**Issue by agrabeli** [ooni/backend#582]
A community member recently raised an important issue: When they test a website (e.g. twitch.tv) many times on a network, the testing of that website gets de-prioritized on all other networks in the country (resulting in only having testing coverage for that website on 1 ASN). 

As an example, they pointed to the testing of twitch.tv in Iran, where we see that it received barely any testing coverage on other networks in the moment when it was tested a lot on one network: https://explorer.ooni.org/chart/mat?probe_cc=IR&test_name=web_connectivity&domain=www.twitch.tv&since=2022-02-01&until=2022-04-12&axis_x=measurement_start_day&axis_y=probe_asn

This occurs because our URL prioritization algorithm (https://github.com/ooni/api/blob/master/newapi/ooniapi/prio.py#L156) is currently configured in such a way that when a URL gets tested a lot, it gets de-prioritized in testing performed in the rest of the country (in an attempt to enable the testing of other URLs as well and ensure greater website testing coverage). 

However, the issue with this is that if a website is blocked and tested a lot on a specific network (because it is blocked), it won't get tested on all other networks in the country, limiting our ability to examine the accessibility of a blocked website across networks in a country. 

It was therefore proposed that we tweak the prioritization algorithm in order to implement this logic on a per ASN level, as opposed to a country-wide level.

**Comment by bassosimone** [comment]
> However, the issue with this is that if a website is blocked and tested a lot on a specific network (because it is blocked), it won't get tested on all other networks in the country, limiting our ability to examine the accessibility of a blocked website across networks in a country.

Yeah, this definitely does not look desirable!

> [...] It was therefore proposed that we tweak the prioritization algorithm in order to implement this logic on a per ASN level, as opposed to a country-wide level.

The proposed solution looks good, but it may be that considering together ASN and country could possibly be even more robust. I am ~worried about ASNs spanning more than one country. Maybe we do not have ASNs spanning more than one country, but maybe we have a few, or maybe we have none but we may have some in the future.

**Comment by FedericoCeratto** [comment]
Related design document: https://docs.google.com/document/d/1fCTU_P6nQVGS1TQ60EnMxWR6Ex5nw2Ug94PfP78uiMc

**Comment by FedericoCeratto** [comment]
Implemeted in https://github.com/ooni/api/pull/296
