### ISSUE TITLE
api [aggregation,list]: add support for passing a list to filters 

### ISSUE THREAD

**Issue by hellais** [ooni/backend#584]
This involves adding support to the aggregation API to take queries such as:
```
test_name=facebook_messenger,telegram,signal
```

**Comment by hellais** [comment]
We should add support for passing in lists to every filter including the `country_code`

**Comment by hellais** [comment]
From #637 

@fortuna wrote:

> I'd like to analyze a country, but restrict to a fixed set of domains, and only for some ASes (the top ones).
> Existing options are bad:

* num_domains queries, fetching all ASes for each domain
* num_ases queries, fetching all domains for each AS
* num_domains * num_ases queries, fetching each (domain, AS) pair.
* The domain SQL filter can be easily changes to a IN operator here:
https://github.com/ooni/api/blob/8aa24669cc0e5aae3b31bd35a2b371ef11a97f77/newapi/ooniapi/measurements.py#L825

* Same for the probe_asn filter at https://github.com/ooni/api/blob/8aa24669cc0e5aae3b31bd35a2b371ef11a97f77/newapi/ooniapi/measurements.py#L777

**Comment by hellais** [comment]
I believe this has been implemented.

@FedericoCeratto can you confirm and if so close the issue?

**Comment by FedericoCeratto** [comment]
@hellais it is. Closing the issue.

**Comment by fortuna** [comment]
It seems https://github.com/ooni/api/pull/324 only added the list filters to MAT, not the measurements API.
@FedericoCeratto is that right?
If so, then this issue is not yet resolved.

**Comment by fortuna** [comment]
Yeah, It looks like the API is still using a single domain:
https://github.com/ooni/api/blob/0901aeac10caedf4dbbc6ab9bee4cc456ff16e79/newapi/ooniapi/measurements.py#L825

**Comment by hellais** [comment]
> It seems https://github.com/ooni/api/pull/324 only added the list filters to MAT, not the measurements API.

That's a good point, thanks for spotting it. I will rename this issue to apply just to MAT and file a new issue for list measurements.

**Comment by hellais** [comment]
Done: https://github.com/ooni/backend/issues/795
