### ISSUE TITLE
API does not permit test_name=stunreachability

### ISSUE THREAD

**Issue by Em4E** [ooni/backend#590]
OONI Explorer exposes an option ***Test Name: STUN Reachability***. But it doesn't work. The API server replies with status 400, saying that "stunreachability" is not a permitted value.

https://api.ooni.io/api/v1/measurements?limit=50&test_name=stunreachability&since=2022-04-02&until=2022-05-03

> ## 400 Error
> ### Bad Request
>
> 'stun_reachability' is not one of ['bridge_reachability', 'dash', 'dns_consistency', 'dnscheck', 'facebook_messenger', 'http_header_field_manipulation', 'http_host', 'http_invalid_request_line', 'http_requests', 'meek_fronted_requests_test', 'multi_protocol_traceroute', 'ndt', 'psiphon', 'riseupvpn', 'signal', 'tcp_connect', 'telegram', 'tor', 'torsf', 'urlgetter', 'vanilla_tor', 'web_connectivity', 'whatsapp']

My goal in wanting to see stunreachability measurements is to get better granularity on torsf failures.

**Comment by hellais** [comment]
Thanks for reporting this, we have this tracked as part of the following issue: https://github.com/ooni/backend/issues/573.
