### ISSUE TITLE
Network Error when trying to access data.

### ISSUE THREAD

**Issue by abhishekvasishtb** [ooni/backend#594]
Hello, When I try to access data at the OONI Explorer page, I get a 'network error'. 
This is the page I'm trying to access
https://explorer.ooni.org/search?since=2022-05-08&until=2022-05-13&probe_cc=PH&test_name=web_connectivity&failure=false&only=confirmed

Thanks.

**Comment by hellais** [comment]
Hi, thanks for reporting this issue. Our measurements API went down for some hours, but we have since restored it.

Apologies for the inconvenience.
