### ISSUE TITLE
Add annotation keys to report filename

### ISSUE THREAD

**Issue by andresazp** [ooni/backend#60]
I would propose to add the option that when setting the report name at oonib.conf we could include different annotation values form specific keys that might be setup if the annotated key is present.

**Example**
for ooniprobe -i example.deck -a **_key_:data**,**_hardcoded-city_:cityname**,

it would be great to allow report names that include the data for the **_hardcoded-city_** or any other key in the filename at oonib

**Comment by hellais** [comment]
Let me see if I understand this correctly, you mean you would like to determine the filename of the report based on something present within annotations?

**Comment by andresazp** [comment]
If at all possible, yes. Obviously it's not something critical, and in a couple of months it's something we might look into ourselves.
But I though of putting the idea here anyways as maybe others could be interested in having too

**Comment by anadahz** [comment]
Thank you for reporting this @andresazp 
This [commit](https://github.com/TheTorProject/ooni-probe/commit/6837a3ccccb01aea0381defa20847001c145f3a1) correctly add (fixed) annotations inside the report file in this form:
`annotations: {key: value}`
Let us know if this works for you.

**Comment by hellais** [comment]
This is no longer relevant given the evolutions of the dataformat.
