### ISSUE TITLE
aggregation API: IPaddr not accepted as domain and input filter

### ISSUE THREAD

**Issue by majakomel** [ooni/backend#603]
Aggregation endpoint currently doesn’t accept IP [domains](https://api.ooni.io/api/v1/aggregation?test_name=web_connectivity&domain=154.35.175.225&since=2022-07-04&until=2022-08-04&axis_x=measurement_start_day) or [inputs](https://api.ooni.io/api/v1/aggregation?test_name=web_connectivity&input=http%3A%2F%2F154.35.175.225%2Ftor%2Fserver%2Fauthority&since=2022-07-04&until=2022-08-04&axis_x=measurement_start_day).

[Measurements](https://api.ooni.io/api/v1/measurements?limit=50&failure=false&domain=154.35.175.225&since=2022-07-04&until=2022-08-04) endpoint for comparison works fine.

**Comment by FedericoCeratto** [comment]
Deployed
