### ISSUE TITLE
pipeline: vanilla_tor scoring is broken

### ISSUE THREAD

**Issue by hellais** [ooni/backend#608]
Here is an example of a measurement of vanilla_tor being blocked: https://explorer.ooni.org/measurement/20220802T215209Z_vanillator_CN_17623_n1_LXFdyo7ao2kE7sQj, but the scores field taken from the API says otherwise: https://api.ooni.io/api/v1/measurement_meta?report_id=20220802T215209Z_vanillator_CN_17623_n1_LXFdyo7ao2kE7sQj.

```
{"anomaly":false,"category_code":null,"confirmed":false,"failure":false,"input":"","measurement_start_time":"2022-08-02T21:55:29Z","measurement_uid":"20220802215530.933188_CN_vanillator_f4e06257ed70aac2","probe_asn":17623,"probe_cc":"CN","report_id":"20220802T215209Z_vanillator_CN_17623_n1_LXFdyo7ao2kE7sQj","scores":"{\"blocking_general\":0.0,\"blocking_global\":0.0,\"blocking_country\":0.0,\"blocking_isp\":0.0,\"blocking_local\":0.0}","test_name":"vanilla_tor","test_start_time":"2022-08-02T21:52:07Z"}
```

**Comment by FedericoCeratto** [comment]
Vanilla Tor scoring was added in https://github.com/ooni/pipeline/pull/242

**Comment by FedericoCeratto** [comment]
Fixed
