### ISSUE TITLE
sysadmin: slack to IRC bridge is broken

### ISSUE THREAD

**Issue by hellais** [ooni/backend#617]
The slack to IRC bridge has not been working since the ~27th of September 2022.

That's based on the fact that it's on that date we got the last messages relayed from IRC onto slack.

I tried doing the usual of restarting the docker service for the slack-irc bridge and doing some tweaks to the config file to no avail.

For context, in the past it broke due to a bug in the upstream: https://github.com/ekmartin/slack-irc/issues/269, which we fixed inside of our fork of it: https://github.com/ooni/sysadmin/issues/481 https://github.com/ooni/slack-irc.

Looking at the logs for slack-irc I see the following:
```
[winston] Attempt to write logs with no transports {"prefix":"coulomb.oftc.net","server":"coulomb.oftc.net","command":"rpl_welcome","rawCommand":"001","commandType":"reply","args":["slacktopus","Welcome to the OFTC Internet Relay Chat Network slacktopus"],"level":"debug","message":"Registered event: "}
[winston] Attempt to write logs with no transports {"level":"info","message":"Tried to send a message to a channel the bot isn't in: "}
```

Yet according to the bot configuration it is part of the channel:
![Screenshot 2022-10-10 at 15 47 43](https://user-images.githubusercontent.com/424620/194881180-a86c75f3-9337-4ce9-aa78-0d5677b1597b.png)

It's worth noting that the integration we are using is a "legacy custom integration", which according to the slack docs is:
> an outdated way for teams to integrate with Slack. These integrations lack newer features and they will be deprecated and possibly removed in the future. We do not recommend their use. Instead, we suggest that you check out their replacement: [Slack apps](https://api.slack.com/start).

Moreover the slack-irc bridge we are using is abbandonware since several years, so we might at this point want to look into replacing it with a new solution altogether.

I know @anadahz has used something different for the #pluggable-transports bridge channel, so any insight he may have on that would be greatly appreciated (perhaps if it's not too much of a hassle we can just add these channels to his bridge).

**Comment by hellais** [comment]
The channels we need to bridge are the following:
```
        "channelMapping": {
            "#kandoo-iran": "#kandoo-iran",
            "#ooni": "#ooni",
            "#ooni-design": "#ooni-design",
            "#ooni-dev": "#ooni-dev",
            "#ooni-entropy": "#ooni-entropy",
            "#tor-meeting": "#tor-meeting"
        },
```

**Comment by agrabeli** [comment]
The bridge is now fixed! Huge thanks to anadahz. <3

**Comment by hellais** [comment]
On Aug 13th it was reported by @sloncocs that it's not working again

**Comment by hellais** [comment]
The bridge is now back online thanks to @anadahz
