### ISSUE TITLE
aggregation: support passing granularity field with values hourly, weekly, monthly

### ISSUE THREAD

**Issue by majakomel** [ooni/backend#623]
https://github.com/ooni/explorer/issues/738

**Comment by FedericoCeratto** [comment]
Allowed granularity:

| Time range  | hour | day | week | month   |
| ------------- | ------------- | ------------- | ------ | --- |
|  <= 1 week   |  o | o |  |   |
| <= 1 month   |   | o |  o  |   |
| <= 1 year  |   |  o | o  | o  |
| > 1 year  |   |    |   | o  |
