### ISSUE TITLE
Implement the backend CRUD for reporting incidents

### ISSUE THREAD

**Issue by hellais** [ooni/backend#630]
New censorship events frequently emerge worldwide on an ongoing basis, but producing an in-depth report and analysis on each event (in a timely manner) is not easily scalable. Moreover, rapid response efforts benefit from censorship findings that are easier and quicker to consume.

We therefore aim to create a Censorship Incident Reporting Platform which will regularly provide short reports with summary information on emergent censorship events based on OONI data and charts. This will enable journalists and human rights defenders to more easily learn about and respond to censorship events. Over time, the platform will become an archive of known censorship incidents from around the world based on OONI network measurement data. 

In developing this platform, we will ensure that it is complementary to existing efforts. For example, OONI is currently a data partner for the Internet Society (ISOC) Pulse project which provides a timeline of internet shutdowns around the world. This project primarily covers internet outages (based on multiple datasets), while OONI’s Censorship Incident Reporting Platform will cover a broader range of blocking events (such as news media and human rights website blocking) based on OONI data. OONI’s Censorship Incident Reporting Platform will also be different (and complementary) to the Tor Project’s Tor Metrics Timeline, which relies on community members to contribute information about censorship events. Instead, the OONI Censorship Incident Reporting Platform will regularly publish short reports that provide charts based on aggregate views of OONI data (which journalists and activists can easily use), linking to relevant OONI measurements (that can serve as evidence of internet censorship), and providing relevant concise interpretation of OONI censorship measurement findings.

**Comment by hellais** [comment]
This is basically having an API to save a MAT chart filter together with a title and description.

**Comment by FedericoCeratto** [comment]
Design document: https://docs.google.com/document/d/1TdMBWD45j3bx7GRMIriMvey72viQeKrx7Ad6DyboLwg/edit

**Comment by hellais** [comment]
We have a deployed prototype of this that was merged as part of ooni/backend#678

**Comment by hellais** [comment]
We are have mostly completed all things required for this, some more needs might emerge as we make progress on the UI

**Comment by FedericoCeratto** [comment]
Also related https://github.com/ooni/backend/pull/700

**Comment by jbonisteel** [comment]
Closing this epic because we launched this on November 30th, 2023. Will spin up new issues and/or epics for future work
