### ISSUE TITLE
[Feature] Make API accept multiple domains and ASNs

### ISSUE THREAD

**Issue by fortuna** [ooni/backend#637]
I'd like to analyze a country, but restrict to a fixed set of domains, and only for some ASes (the top ones). 
Existing options are bad:
- num_domains queries, fetching all ASes for each domain
- num_ases queries, fetching all domains for each AS
- num_domains * num_ases queries, fetching each (domain, AS) pair.

The `domain` SQL filter can be easily changes to a `IN` operator here:
https://github.com/ooni/api/blob/8aa24669cc0e5aae3b31bd35a2b371ef11a97f77/newapi/ooniapi/measurements.py#L825

Same for the `probe_asn` filter at https://github.com/ooni/api/blob/8aa24669cc0e5aae3b31bd35a2b371ef11a97f77/newapi/ooniapi/measurements.py#L777

**Comment by hellais** [comment]
Thanks for requesting this, it is indeed a much needed feature!

Closing this in favour of the existing issue: https://github.com/ooni/backend/issues/584
