### ISSUE TITLE
api: Drop validation of test_names and drop API endpoint for test_names

### ISSUE THREAD

**Issue by hellais** [ooni/backend#639]
With @majakomel we concluded that it's most useful to have the list of test_names and category codes inside of Explorer.

We need to rebuild the list there anyways (for localizing it and adding icons, colors, etc.), so it doesn't make sense to have it duplicated in explorer.

By removing the check on the search API, we can avoid having to update two projects whenever a new test is deployed.

**Comment by FedericoCeratto** [comment]
Implemented in d96b04dc0ab457c7a6a74ec74728b470b72042ec
