### ISSUE TITLE
run: add backend support for giving out OONI Run links to clients

### ISSUE THREAD

**Issue by hellais** [ooni/backend#677]
This is related to https://github.com/ooni/backend/issues/676 and contrary to what is outlined in the specification, this might in the end work a bit differently by integrating this component directly into the check-in API.

**Comment by hellais** [comment]
A first iteration of this is implemented as part of: https://github.com/ooni/backend/pull/678

**Comment by jbonisteel** [comment]
Same status as last time - no new requirements right now

**Comment by jbonisteel** [comment]
I am going to close this issue for now and we will open new ones if new requirements, bugs or changes pop up down the road.
