### ISSUE TITLE
Sane defaults for bouncer.yaml and policy.yaml

### ISSUE THREAD

**Issue by anadahz** [ooni/backend#71]
We should set some sane defaults for both bouncer.yaml and policy.yaml.
The current (default) [bouncer.yaml](https://github.com/TheTorProject/ooni-backend/blob/master/data/bouncer.yaml) is quite strict.
We should change the default [policy.yaml](https://github.com/TheTorProject/ooni-backend/blob/master/data/policy.yaml) accordingly.

**Comment by bassosimone** [comment]
Closing this issue, which is clearly obsolete at this point.
