### ISSUE TITLE
Database backup: safer table backup workflow

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#767]
Improve https://github.com/ooni/backend/blob/master/analysis/ooni_db_backup.py to create a safer workflow. Each table found in the `default` database should be listed in `/etc/ooni/db-backup.conf` and flagged for public backup or private backup or no backup.

If any table is unlisted the DB backup tool should send an alert on Slack
 
Related to #766

**Comment by hellais** [comment]
See: https://github.com/ooni/backend/issues/765
