### ISSUE TITLE
Test helper rotation: update TLS certs  on all hosts

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#777]
When a test helper is deployed by the rotation script a fresh TLS cert is generated using the Digital Ocean API. The cert is deployed on the new host.
The rotation script can be tweaked to [attempt to] update the cert on all existing test helper hosts instead.

**Comment by hellais** [comment]
We should move the test helper rotation from the custom script into the new devops pattern. See: https://docs.ooni.org/backend/ooniapi/services/
