### ISSUE TITLE
Set upper bound on expiry time for web connectivity test helper 

### ISSUE THREAD

**Issue by hellais** [ooni/backend#82]
The legacy (python-based) web_connectivity test helper will reset the expiry time on the cache every time somebody request the resource again. This means that if a certain resource is requested many times it could end up being served from the cache indefinitely. It would be ideal to instead set an upper bound on how long it stays in cache so that after that fixed amount of time passes it is expired.

As pointed out by @bassosimone in https://github.com/TheTorProject/ooni-backend/pull/63#issuecomment-222305811

**Comment by bassosimone** [comment]
I need to discuss whether to close this issue or not with @FedericoCeratto. We are going to use Nginx for caching with the new test helper implementation. The question is whether Nginx _could_ cache a response for an infinite time.

**Comment by FedericoCeratto** [comment]
Nginx follows HTTP caching standard practices: as long as the **new** TH sets the expiration header to a time in the near future, Nginx will drop the cache content after the expiry

**Comment by bassosimone** [comment]
@FedericoCeratto since it's not setting any expiration, I suppose I MUST add headers, correct?

**Comment by bassosimone** [comment]
No, @FedericoCeratto clarified that Nginx already overrides cache headers and so there is no need for me to do anything here.

**Comment by bassosimone** [comment]
I am going to optimistically assume we'll not rollback the change that makes all probes use the new webconnectivity TH and close this issue, which is related to the previous TH implementation.
