### ISSUE TITLE
Avoid re-writing the cached value when more requests come for the same url or socket

### ISSUE THREAD

**Issue by hellais** [ooni/backend#83]
Currently in the web_connectivity test helper if two requests come at the same time for a given URL and it's not cached we will have `MISS` in the and we will try to obtain the value from the network twice and the one that returns the latest will overwrite the cache.

Probably what we want to be doing is acquire the lock on the cache as soon as we begin doing any resource lookup so that the following requests will be waiting on the lock for the cache lookup and will get the cached value as soon as the lock is released (the resource has been cached)

As suggested by @bassosimone suggested in https://github.com/TheTorProject/ooni-backend/pull/63#issuecomment-222305811

**Comment by bassosimone** [comment]
I am going to assume the Ngnix cache is implemented properly and we don't need to worry about this topic.
