### ISSUE TITLE
Improvements to deployment strategy for ooni-backend

### ISSUE THREAD

**Issue by hellais** [ooni/backend#87]
This is somewhat related to #86 as well, but in general we need to come up with a good strategy for handling the deployment of new versions of ooni-backend.

We discussed various ways of doing this with @anadahz, but didn't come up with a good solution.

Assuming something for #86 is implemented there is the issue that we want to minimise the amount of downtime and have some way of redirecting clients from the old installation to the new installation once it comes online.
## Red-black deployment strategy

One proposed solution was to do a red-black deployment strategy where when the system is operational we have the following containers:
- Container A - Bouncer with address bouncer.ooni.io
- Container B - With Collector and test helpers with address a.collector.ooni.io

When we need to deploy a new version of the collector and bouncer the strategy could be to spin up other 2 containers C (with collector address b.collector.ooni.io) and D (with bouncer).
The new bouncer will be setup to redirect all users traffic to `b.collector.ooni.io`. Once these two machines are online the port mapping is swapped to redirect bouncer traffic to the new bouncer.
The Container B (a.collector.ooni.io) is monitored and when it stops being used, because all users are now using the new collector and test helpers on container C it is safe to shut down the old bouncer and collector.

The benefit I see of this strategy is that it allows us to do testing of the new collector and test helpers before they are rolled over to production, but does have quite a bit of complication in it.

This solution would work also if a fix for #86 is not implemented and hence is why it was proposed in this context.
## Simple solution based on port mapping

Another possibly simpler approach (given that a fix for #86) is to keep the containers as they currently are in the same directory, but rely on iptables (or similar port mapping) to switch the mapping over to the new collector/bouncer once it has been taken up.

**Comment by anadahz** [comment]
First some points on how we end up to this discussion.
Currently the TLS "logic" of the `web_connectivity` test is developed to be in the bouncer; a component that needs to be always online since it's the discovery mechanism in ooni-backend. It [seems](https://github.com/TheTorProject/ooni-backend/blob/master/oonib/oonibackend.py#L45) there is no clean way apart from killing and restarting ooni-backend to reload and re-read a TLS certificate.

Adding another potential solution.

## Load balancing
Implement a load balancing logic to keep track of asynchronous requests (perhaps with the help of #86 ) or even natively support load balancing capabilities to bouncer. Twisted [supports](https://twistedmatrix.com/documents/current/core/howto/endpoints.html#servers) the HAProxy [protocol](http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt) specification.

**Comment by bassosimone** [comment]
After reading yesterday's IRC log, I have the following comment regarding uploading everything at the end of a test. I do think that uploading in one batch should be supported but I do not think doing that is in general a good idea.

Think about it: many tests generates lots of data and hence, if the upload is done at the end, it would clog the possibly-slow user network for quite some time. If / when this happens, the user may become impatient and kill ooni-probe. In the same vein, we already know that there are users starting decks that interrupt them in the middle. In such case, with uploading at the end, no report would ever be sent, while some data would be sent with incremental upload.

For these reasons, I am against removing the possibility of uploading reports incrementally, but at the same time I recognize that fingerprintability also matters and hence different strategies should be possible depending on what the user wants.

My suggestion to move forward is to leverage the filesystem as a database for the time being, as proposed by @hellais on IRC. If we want to do load balancing (a thing that could be useful but I won't implement load balancing to solve this problem of upgrading), this state should be moved from the file system to somewhere else that is accessible on the network. If I recall correctly how queues like the one we have in the backend work, they do this job (correct me if wrong) in the sense that you can post updates (i.e. new reports) on open topics (i.e. reports that have not been closed yet).

Does this make sense?

**Comment by FedericoCeratto** [comment]
Related to https://github.com/ooni/backend/issues/437

**Comment by hellais** [comment]
We now have a strategy of this sorts in place. Closing.
