### ISSUE TITLE
Validate the bouncer configuration when ooni-backend first starts

### ISSUE THREAD

**Issue by hellais** [ooni/backend#94]
Currently if there is an invalid bouncer configuration the user will notice it only once the service has started.

On first start it should validate if the bouncer configuration is valid and if not exit with some error.

**Comment by joelanders** [comment]
Similar to https://github.com/TheTorProject/ooni-sysadmin/issues/18

**Comment by hellais** [comment]
Ah yes indeed. I did seem to recall the was already a ticket open about this! Though that one is in the wrong component. I am going to close that other one and just keep this one open.

**Comment by bassosimone** [comment]
We're disposing of this code. So we don't care about keeping this issue open.
